In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [152]:
# reading the dataset as pandas dataframe

df_stores = pd.read_csv(r"/Users/gokul/My Apple/vs_code_practice/retail_sales_forecast/data/stores_data_set.csv")
df_sales = pd.read_csv(r"/Users/gokul/My Apple/vs_code_practice/retail_sales_forecast/data/sales_data_set.csv")
df_sales_2 = pd.read_csv(r"/Users/gokul/My Apple/vs_code_practice/retail_sales_forecast/data/sales_data_set2.csv")
df_features = pd.read_csv(r"/Users/gokul/My Apple/vs_code_practice/retail_sales_forecast/data/Features_data_set.csv")

In [153]:
display(df_stores)
print("Sales Dataframe")
display(df_sales)
print("Sales Dataframe 2")
display(df_sales_2)
print("Features Dataframe")
df_features

Store Type    Size
0       1    A  151315
1       2    A  202307
2       3    B   37392
3       4    A  205863
4       5    B   34875
5       6    A  202505
6       7    B   70713
7       8    A  155078
8       9    B  125833
9      10    B  126512
10     11    A  207499
11     12    B  112238
12     13    A  219622
13     14    A  200898
14     15    B  123737
15     16    B   57197
16     17    B   93188
17     18    B  120653
18     19    A  203819
19     20    A  203742
20     21    B  140167
21     22    B  119557
22     23    B  114533
23     24    A  203819
24     25    B  128107
25     26    A  152513
26     27    A  204184
27     28    A  206302
28     29    B   93638
29     30    C   42988
30     31    A  203750
31     32    A  203007
32     33    A   39690
33     34    A  158114
34     35    B  103681
35     36    A   39910
36     37    C   39910
37     38    C   39690
38     39    A  184109
39     40    A  155083
40     41    A  196321
41     42    C   39690
42     43    C   41062
43     44    C   39910
44     45    B  118221

Sales Dataframe


Store  Dept        Date  Weekly_Sales  IsHoliday
0           1     1  05/02/2010      24924.50      False
1           1     1  12/02/2010      46039.49       True
2           1     1  19/02/2010      41595.55      False
3           1     1  26/02/2010      19403.54      False
4           1     1  05/03/2010      21827.90      False
...       ...   ...         ...           ...        ...
421565     45    98  28/09/2012        508.37      False
421566     45    98  05/10/2012        628.10      False
421567     45    98  12/10/2012       1061.02      False
421568     45    98  19/10/2012        760.01      False
421569     45    98  26/10/2012       1076.80      False

[421570 rows x 5 columns]

Sales Dataframe 2


Store  Dept        Date  IsHoliday
0           1     1  2012-11-02      False
1           1     1  2012-11-09      False
2           1     1  2012-11-16      False
3           1     1  2012-11-23       True
4           1     1  2012-11-30      False
...       ...   ...         ...        ...
115059     45    98  2013-06-28      False
115060     45    98  2013-07-05      False
115061     45    98  2013-07-12      False
115062     45    98  2013-07-19      False
115063     45    98  2013-07-26      False

[115064 rows x 4 columns]

Features Dataframe


Store        Date  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
0         1  05/02/2010        42.31       2.572        NaN        NaN   
1         1  12/02/2010        38.51       2.548        NaN        NaN   
2         1  19/02/2010        39.93       2.514        NaN        NaN   
3         1  26/02/2010        46.63       2.561        NaN        NaN   
4         1  05/03/2010        46.50       2.625        NaN        NaN   
...     ...         ...          ...         ...        ...        ...   
8185     45  28/06/2013        76.05       3.639    4842.29     975.03   
8186     45  05/07/2013        77.50       3.614    9090.48    2268.58   
8187     45  12/07/2013        79.37       3.614    3789.94    1827.31   
8188     45  19/07/2013        82.84       3.737    2961.49    1047.07   
8189     45  26/07/2013        76.06       3.804     212.02     851.73   

      MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  
0           NaN        NaN        NaN  211.096358         8.106      False  
1           NaN        NaN        NaN  211.242170         8.106       True  
2           NaN        NaN        NaN  211.289143         8.106      False  
3           NaN        NaN        NaN  211.319643         8.106      False  
4           NaN        NaN        NaN  211.350143         8.106      False  
...         ...        ...        ...         ...           ...        ...  
8185       3.00    2449.97    3169.69         NaN           NaN      False  
8186     582.74    5797.47    1514.93         NaN           NaN      False  
8187      85.72     744.84    2150.36         NaN           NaN      False  
8188     204.19     363.00    1059.46         NaN           NaN      False  
8189       2.06      10.88    1864.57         NaN           NaN      False  

[8190 rows x 12 columns]

**Lets take the stores dataframe**

**Store:** Store number

**Type:** Type of the store

**Size:** Size of the atore i.e Area

In [9]:
df_stores['Type'].value_counts()

Type
A    22
B    17
C     6
Name: count, dtype: int64

**Sales Dataframe**

**Store:** Store number

**Dept:** Specific dept in the store

**Date:** Every friday of the week

**Weekly Sales:** Total sales of that week

**IsHoliday:** Whether it is holiday or not

In [15]:
print(df_sales['Dept'].unique())
df_sales['Dept'].nunique()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 40 41 42 44 45 46 47 48 49 51 52
 54 55 56 58 59 60 67 71 72 74 77 78 79 80 81 82 83 85 87 90 91 92 93 94
 95 96 97 98 99 39 50 43 65]


81

We have 45 stores and 81 departments.

So we can say that one store has several departments, which doesn't mean all the dept. are present in all the stores

In [17]:
sd_pivot = pd.pivot_table(df_sales, index= 'Store', columns= 'Dept', values= 'Weekly_Sales', aggfunc= np.mean)
sd_pivot.head(10)

/var/folders/dm/tc0kcybn1s14gt0x19gzm_jm0000gn/T/ipykernel_82086/2603926814.py:1: FutureWarning: The provided callable <function mean at 0x104c06660> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass 'mean' instead.
  sd_pivot = pd.pivot_table(df_sales, index= 'Store', columns= 'Dept', values= 'Weekly_Sales', aggfunc= np.mean)


Dept             1              2             3             4             5   \
Store                                                                          
1      22513.322937   46102.090420  13150.478042  36964.154476  24257.941119   
2      30777.980769   65912.922517  17476.563357  45607.666573  30555.315315   
3       7328.621049   16841.775664   5509.300769   8434.186503  11695.366573   
4      36979.940070   93639.315385  19012.491678  56603.400140  45668.406783   
5       9774.553077   12317.953287   4101.085175   9860.806783   6699.202238   
6      23867.553776   50269.437273  16806.638811  34187.366503  34465.307622   
7       9542.801259   22603.690769   8633.536923  14950.518601  13860.350490   
8      14789.827343   35729.821748  10683.305105  21089.309301  19838.849231   
9      11846.558252   24969.477413   7497.356783  17165.947762  19282.746014   
10     39925.138951  109795.291469  32086.181469  48579.826364  58373.460280   

Dept             6             7             8             9             10  \
Store                                                                         
1       4801.780140  24566.487413  35718.257622  28062.052238  31033.386364   
2       6808.382517  40477.837063  58707.369441  34375.864476  38845.854476   
3       2012.411818  10044.341608   8310.254196   9062.007692  10871.944126   
4       8241.777692  50728.151399  62949.723776  34437.170979  37269.667413   
5       1191.057622   6124.484336  13735.709441   7919.805944   9783.395385   
6       7225.566643  34526.870420  47577.719790  48271.060140  47436.477902   
7       6329.928811  10925.757063  13970.619371  29722.736084  21136.560280   
8       3395.425455  20268.743776  26438.524336  11792.661678  20666.433776   
9       2806.416364  13826.694336  21424.470699  13196.569720  12810.480350   
10     10556.550769  58964.715664  86739.846643  64436.722517  48108.063497   

Dept   ...            90            91             92            93  \
Store  ...                                                            
1      ...  82427.547832  64238.943427  135458.969510  71699.182378   
2      ...  97611.537133  80610.380350  164840.230979  70581.977063   
3      ...   1540.049161    318.685594    7568.280210           NaN   
4      ...  89248.965524  66535.407203  159365.107902  67815.163007   
5      ...   3059.520000   1457.221678    7759.205594           NaN   
6      ...  53715.366084  45270.405175   99024.796503  41359.651189   
7      ...  13858.405874  10263.880000   26530.890559   1328.178252   
8      ...  39333.566154  31530.560909   60465.630000  27515.635315   
9      ...   2981.249510    869.273287   14123.063147     21.240000   
10     ...  14291.869790  12703.554406   50450.731958   1420.418462   

Dept             94             95            96            97            98  \
Store                                                                          
1      63180.568182  120772.062168  33251.831639  35207.348811  11827.770769   
2      70018.672517  143588.751888  34319.063846  40697.204056  14035.400839   
3        656.294444   15745.528252   3934.540000    343.437357     30.570833   
4      68159.106573  147236.473706  38346.573077  39339.238951  15009.249371   
5        411.431486   19340.693986   5985.671119    667.070315     29.976087   
6      41701.693497   89208.786294  30450.542238  20637.667063   9728.100629   
7        699.332522   34208.097273   1123.383217   4374.927902    260.886596   
8      25442.578042   62951.463706     16.986667  16978.366503   6880.466434   
9        599.112568   29575.050769   3596.107762    372.655556     27.930000   
10       393.833168   73344.654685  11079.676643   5323.506503    198.179091   

Dept           99  
Store              
1      306.091081  
2      475.896905  
3             NaN  
4      623.182381  
5             NaN  
6      388.636750  
7       15.000000  
8      298.153714  
9             NaN  
10            NaN  

[10 rows x 81 columns]

## Handling Missing values

In [59]:
df_features

Store        Date  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
0         1  05/02/2010        42.31       2.572        NaN        NaN   
1         1  12/02/2010        38.51       2.548        NaN        NaN   
2         1  19/02/2010        39.93       2.514        NaN        NaN   
3         1  26/02/2010        46.63       2.561        NaN        NaN   
4         1  05/03/2010        46.50       2.625        NaN        NaN   
...     ...         ...          ...         ...        ...        ...   
8185     45  28/06/2013        76.05       3.639    4842.29     975.03   
8186     45  05/07/2013        77.50       3.614    9090.48    2268.58   
8187     45  12/07/2013        79.37       3.614    3789.94    1827.31   
8188     45  19/07/2013        82.84       3.737    2961.49    1047.07   
8189     45  26/07/2013        76.06       3.804     212.02     851.73   

      MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  
0           NaN        NaN        NaN  211.096358         8.106      False  
1           NaN        NaN        NaN  211.242170         8.106       True  
2           NaN        NaN        NaN  211.289143         8.106      False  
3           NaN        NaN        NaN  211.319643         8.106      False  
4           NaN        NaN        NaN  211.350143         8.106      False  
...         ...        ...        ...         ...           ...        ...  
8185       3.00    2449.97    3169.69         NaN           NaN      False  
8186     582.74    5797.47    1514.93         NaN           NaN      False  
8187      85.72     744.84    2150.36         NaN           NaN      False  
8188     204.19     363.00    1059.46         NaN           NaN      False  
8189       2.06      10.88    1864.57         NaN           NaN      False  

[8190 rows x 12 columns]

In [60]:
df_features.isna().sum()

Store              0
Date               0
Temperature        0
Fuel_Price         0
MarkDown1       4158
MarkDown2       5269
MarkDown3       4577
MarkDown4       4726
MarkDown5       4140
CPI              585
Unemployment     585
IsHoliday          0
dtype: int64

In [61]:
df_feature_store = pd.merge(df_stores, df_features, on= 'Store', how= 'inner')
df_feature_store

Store Type    Size        Date  Temperature  Fuel_Price  MarkDown1  \
0         1    A  151315  05/02/2010        42.31       2.572        NaN   
1         1    A  151315  12/02/2010        38.51       2.548        NaN   
2         1    A  151315  19/02/2010        39.93       2.514        NaN   
3         1    A  151315  26/02/2010        46.63       2.561        NaN   
4         1    A  151315  05/03/2010        46.50       2.625        NaN   
...     ...  ...     ...         ...          ...         ...        ...   
8185     45    B  118221  28/06/2013        76.05       3.639    4842.29   
8186     45    B  118221  05/07/2013        77.50       3.614    9090.48   
8187     45    B  118221  12/07/2013        79.37       3.614    3789.94   
8188     45    B  118221  19/07/2013        82.84       3.737    2961.49   
8189     45    B  118221  26/07/2013        76.06       3.804     212.02   

      MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  \
0           NaN        NaN        NaN        NaN  211.096358         8.106   
1           NaN        NaN        NaN        NaN  211.242170         8.106   
2           NaN        NaN        NaN        NaN  211.289143         8.106   
3           NaN        NaN        NaN        NaN  211.319643         8.106   
4           NaN        NaN        NaN        NaN  211.350143         8.106   
...         ...        ...        ...        ...         ...           ...   
8185     975.03       3.00    2449.97    3169.69         NaN           NaN   
8186    2268.58     582.74    5797.47    1514.93         NaN           NaN   
8187    1827.31      85.72     744.84    2150.36         NaN           NaN   
8188    1047.07     204.19     363.00    1059.46         NaN           NaN   
8189     851.73       2.06      10.88    1864.57         NaN           NaN   

      IsHoliday  
0         False  
1          True  
2         False  
3         False  
4         False  
...         ...  
8185      False  
8186      False  
8187      False  
8188      False  
8189      False  

[8190 rows x 14 columns]

In [62]:
df_feature_store.dtypes

Store             int64
Type             object
Size              int64
Date             object
Temperature     float64
Fuel_Price      float64
MarkDown1       float64
MarkDown2       float64
MarkDown3       float64
MarkDown4       float64
MarkDown5       float64
CPI             float64
Unemployment    float64
IsHoliday          bool
dtype: object

In [63]:
df_feature_store['Date'] = pd.to_datetime(df_feature_store['Date'], format= '%d/%m/%Y')

In [64]:
# adding a new column for week numbers with respective to the date

df_feature_store['Week_Number'] = df_feature_store['Date'].dt.isocalendar().week

### Assigning Values for IsHoliday column

In [65]:
# getting the dates of holidays

df_feature_store[df_feature_store['IsHoliday'] == True]['Date'].unique()

<DatetimeArray>
['2010-02-12 00:00:00', '2010-09-10 00:00:00', '2010-11-26 00:00:00',
 '2010-12-31 00:00:00', '2011-02-11 00:00:00', '2011-09-09 00:00:00',
 '2011-11-25 00:00:00', '2011-12-30 00:00:00', '2012-02-10 00:00:00',
 '2012-09-07 00:00:00', '2012-11-23 00:00:00', '2012-12-28 00:00:00',
 '2013-02-08 00:00:00']
Length: 13, dtype: datetime64[ns]

In [66]:
# getting the count of holidays by week numbers 

df_feature_store[df_feature_store['IsHoliday'] == True]['Week_Number'].value_counts()

Week_Number
6     180
36    135
47    135
52    135
Name: count, dtype: Int64

Only 4 main holidays is available in the data.

By comparing the date and week number we can say the following speculation.

**WEEK 6:** Super Bowl is an unofficial national holiday in the United States, which falls in first or second sunday of february

**WEEK 36:** Labor Day is on the first Monday of September every year in U and it falls in week 36 or 37 of the year

**WEEK 47:** Thanksgiving, which occurs on the fourth Thursday in November, which comes in week 47 or week 48

**WEEK 52** Christmas is observed primarily on December 25, which probably comes in the last week of the year


In [68]:
# replacing the IsHoliday values with the respective holiday occasion

df_feature_store['IsHoliday'] = np.where((df_feature_store['IsHoliday'] == True) & (df_feature_store['Week_Number'] == 6), 'Super Bowl',
                                np.where((df_feature_store['IsHoliday'] == True) & (df_feature_store['Week_Number'] == 36), 'Labor Day',
                                np.where((df_feature_store['IsHoliday'] == True) & (df_feature_store['Week_Number'] == 47), 'Thanksgiving',
                                np.where((df_feature_store['IsHoliday'] == True) & (df_feature_store['Week_Number'] == 52), 'Christmas', 'No Holiday'))))


In [69]:
df_feature_store['IsHoliday'].value_counts()

IsHoliday
No Holiday      7605
Super Bowl       180
Labor Day        135
Thanksgiving     135
Christmas        135
Name: count, dtype: int64

In [88]:
df_feature_store

Store Type    Size       Date  Temperature  Fuel_Price  MarkDown1  \
0         1    A  151315 2010-02-05        42.31       2.572        NaN   
1         1    A  151315 2010-02-12        38.51       2.548        NaN   
2         1    A  151315 2010-02-19        39.93       2.514        NaN   
3         1    A  151315 2010-02-26        46.63       2.561        NaN   
4         1    A  151315 2010-03-05        46.50       2.625        NaN   
...     ...  ...     ...        ...          ...         ...        ...   
8185     45    B  118221 2013-06-28        76.05       3.639    4842.29   
8186     45    B  118221 2013-07-05        77.50       3.614    9090.48   
8187     45    B  118221 2013-07-12        79.37       3.614    3789.94   
8188     45    B  118221 2013-07-19        82.84       3.737    2961.49   
8189     45    B  118221 2013-07-26        76.06       3.804     212.02   

      MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  \
0           NaN        NaN        NaN        NaN  211.096358         8.106   
1           NaN        NaN        NaN        NaN  211.242170         8.106   
2           NaN        NaN        NaN        NaN  211.289143         8.106   
3           NaN        NaN        NaN        NaN  211.319643         8.106   
4           NaN        NaN        NaN        NaN  211.350143         8.106   
...         ...        ...        ...        ...         ...           ...   
8185     975.03       3.00    2449.97    3169.69         NaN           NaN   
8186    2268.58     582.74    5797.47    1514.93         NaN           NaN   
8187    1827.31      85.72     744.84    2150.36         NaN           NaN   
8188    1047.07     204.19     363.00    1059.46         NaN           NaN   
8189     851.73       2.06      10.88    1864.57         NaN           NaN   

       IsHoliday  Week_Number  
0     No Holiday            5  
1     Super Bowl            6  
2     No Holiday            7  
3     No Holiday            8  
4     No Holiday            9  
...          ...          ...  
8185  No Holiday           26  
8186  No Holiday           27  
8187  No Holiday           28  
8188  No Holiday           29  
8189  No Holiday           30  

[8190 rows x 15 columns]

### Markdown null values

In [71]:
# separate dataframe having all markdown values as null

markdown_null = df_feature_store[(df_feature_store.MarkDown1.isna()==True) & (df_feature_store.MarkDown2.isna()==True) & 
                                 (df_feature_store.MarkDown3.isna()==True) & (df_feature_store.MarkDown4.isna()==True) & (df_feature_store.MarkDown5.isna()==True)]

markdown_null

Store Type    Size       Date  Temperature  Fuel_Price  MarkDown1  \
0         1    A  151315 2010-02-05        42.31       2.572        NaN   
1         1    A  151315 2010-02-12        38.51       2.548        NaN   
2         1    A  151315 2010-02-19        39.93       2.514        NaN   
3         1    A  151315 2010-02-26        46.63       2.561        NaN   
4         1    A  151315 2010-03-05        46.50       2.625        NaN   
...     ...  ...     ...        ...          ...         ...        ...   
8095     45    B  118221 2011-10-07        55.82       3.583        NaN   
8096     45    B  118221 2011-10-14        63.82       3.541        NaN   
8097     45    B  118221 2011-10-21        59.60       3.570        NaN   
8098     45    B  118221 2011-10-28        51.78       3.569        NaN   
8099     45    B  118221 2011-11-04        43.92       3.551        NaN   

      MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  \
0           NaN        NaN        NaN        NaN  211.096358         8.106   
1           NaN        NaN        NaN        NaN  211.242170         8.106   
2           NaN        NaN        NaN        NaN  211.289143         8.106   
3           NaN        NaN        NaN        NaN  211.319643         8.106   
4           NaN        NaN        NaN        NaN  211.350143         8.106   
...         ...        ...        ...        ...         ...           ...   
8095        NaN        NaN        NaN        NaN  187.483796         8.523   
8096        NaN        NaN        NaN        NaN  187.691748         8.523   
8097        NaN        NaN        NaN        NaN  187.784620         8.523   
8098        NaN        NaN        NaN        NaN  187.877491         8.523   
8099        NaN        NaN        NaN        NaN  187.970363         8.523   

       IsHoliday  Week_Number  
0     No Holiday            5  
1     Super Bowl            6  
2     No Holiday            7  
3     No Holiday            8  
4     No Holiday            9  
...          ...          ...  
8095  No Holiday           40  
8096  No Holiday           41  
8097  No Holiday           42  
8098  No Holiday           43  
8099  No Holiday           44  

[4140 rows x 15 columns]

All the 5 markdown has 4140 null values (markdown_null dataframe)

Markdown data with all null values is present until 04-11-2011

Hence Markdown data is available only after 04-11-2011

In [89]:
# splitting to separate dataframes with the date as null and not null

# all the markdown values are null
markdown_null = df_feature_store[df_feature_store.Date <= '2011-11-04']
markdown_null.reset_index(drop = True, inplace = True)

#random null values in markdown
markdown_notnull_1 = df_feature_store[df_feature_store.Date > '2011-11-04']
markdown_notnull_1.reset_index(drop = True, inplace = True)

In [90]:
markdown_null

Store Type    Size       Date  Temperature  Fuel_Price  MarkDown1  \
0         1    A  151315 2010-02-05        42.31       2.572        NaN   
1         1    A  151315 2010-02-12        38.51       2.548        NaN   
2         1    A  151315 2010-02-19        39.93       2.514        NaN   
3         1    A  151315 2010-02-26        46.63       2.561        NaN   
4         1    A  151315 2010-03-05        46.50       2.625        NaN   
...     ...  ...     ...        ...          ...         ...        ...   
4135     45    B  118221 2011-10-07        55.82       3.583        NaN   
4136     45    B  118221 2011-10-14        63.82       3.541        NaN   
4137     45    B  118221 2011-10-21        59.60       3.570        NaN   
4138     45    B  118221 2011-10-28        51.78       3.569        NaN   
4139     45    B  118221 2011-11-04        43.92       3.551        NaN   

      MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  \
0           NaN        NaN        NaN        NaN  211.096358         8.106   
1           NaN        NaN        NaN        NaN  211.242170         8.106   
2           NaN        NaN        NaN        NaN  211.289143         8.106   
3           NaN        NaN        NaN        NaN  211.319643         8.106   
4           NaN        NaN        NaN        NaN  211.350143         8.106   
...         ...        ...        ...        ...         ...           ...   
4135        NaN        NaN        NaN        NaN  187.483796         8.523   
4136        NaN        NaN        NaN        NaN  187.691748         8.523   
4137        NaN        NaN        NaN        NaN  187.784620         8.523   
4138        NaN        NaN        NaN        NaN  187.877491         8.523   
4139        NaN        NaN        NaN        NaN  187.970363         8.523   

       IsHoliday  Week_Number  
0     No Holiday            5  
1     Super Bowl            6  
2     No Holiday            7  
3     No Holiday            8  
4     No Holiday            9  
...          ...          ...  
4135  No Holiday           40  
4136  No Holiday           41  
4137  No Holiday           42  
4138  No Holiday           43  
4139  No Holiday           44  

[4140 rows x 15 columns]

In [91]:
#null values in markdown_null dataframe

print('Null values : ', {f'MarkDown{i}': markdown_null[f'MarkDown{i}'].isna().sum() for i in range(1,6)})

Null values :  {'MarkDown1': 4140, 'MarkDown2': 4140, 'MarkDown3': 4140, 'MarkDown4': 4140, 'MarkDown5': 4140}


In [92]:
markdown_notnull_1

Store Type    Size       Date  Temperature  Fuel_Price  MarkDown1  \
0         1    A  151315 2011-11-11        59.11       3.297   10382.90   
1         1    A  151315 2011-11-18        62.25       3.308    6074.12   
2         1    A  151315 2011-11-25        60.14       3.236     410.31   
3         1    A  151315 2011-12-02        48.91       3.172    5629.51   
4         1    A  151315 2011-12-09        43.93       3.158    4640.65   
...     ...  ...     ...        ...          ...         ...        ...   
4045     45    B  118221 2013-06-28        76.05       3.639    4842.29   
4046     45    B  118221 2013-07-05        77.50       3.614    9090.48   
4047     45    B  118221 2013-07-12        79.37       3.614    3789.94   
4048     45    B  118221 2013-07-19        82.84       3.737    2961.49   
4049     45    B  118221 2013-07-26        76.06       3.804     212.02   

      MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  \
0       6115.67     215.07    2406.62    6551.42  217.998085         7.866   
1        254.39      51.98     427.39    5988.57  218.220509         7.866   
2         98.00   55805.51       8.00     554.92  218.467621         7.866   
3         68.00    1398.11    2084.64   20475.32  218.714733         7.866   
4         19.00     105.02    3639.42   14461.82  218.961846         7.866   
...         ...        ...        ...        ...         ...           ...   
4045     975.03       3.00    2449.97    3169.69         NaN           NaN   
4046    2268.58     582.74    5797.47    1514.93         NaN           NaN   
4047    1827.31      85.72     744.84    2150.36         NaN           NaN   
4048    1047.07     204.19     363.00    1059.46         NaN           NaN   
4049     851.73       2.06      10.88    1864.57         NaN           NaN   

         IsHoliday  Week_Number  
0       No Holiday           45  
1       No Holiday           46  
2     Thanksgiving           47  
3       No Holiday           48  
4       No Holiday           49  
...            ...          ...  
4045    No Holiday           26  
4046    No Holiday           27  
4047    No Holiday           28  
4048    No Holiday           29  
4049    No Holiday           30  

[4050 rows x 15 columns]

In [93]:
#null values in markdown_notnull dataframe

print('Null values : ', {f'MarkDown{i}': markdown_notnull_1[f'MarkDown{i}'].isna().sum() for i in range(1,6)})

Null values :  {'MarkDown1': 18, 'MarkDown2': 1129, 'MarkDown3': 437, 'MarkDown4': 586, 'MarkDown5': 0}


In [94]:
# filling the random markdown null values as 0

markdown_notnull = markdown_notnull_1.copy()

for i in range(1,6):
    markdown_notnull[f'MarkDown{i}'].fillna(0, inplace = True)

In [95]:
print('Null values : ', {f'MarkDown{i}': markdown_notnull[f'MarkDown{i}'].isna().sum() for i in range(1,6)})

Null values :  {'MarkDown1': 0, 'MarkDown2': 0, 'MarkDown3': 0, 'MarkDown4': 0, 'MarkDown5': 0}


In [96]:
markdown_notnull.isna().sum()

Store             0
Type              0
Size              0
Date              0
Temperature       0
Fuel_Price        0
MarkDown1         0
MarkDown2         0
MarkDown3         0
MarkDown4         0
MarkDown5         0
CPI             585
Unemployment    585
IsHoliday         0
Week_Number       0
dtype: int64

### CPI & Unemployment

In [97]:
markdown_notnull

Store Type    Size       Date  Temperature  Fuel_Price  MarkDown1  \
0         1    A  151315 2011-11-11        59.11       3.297   10382.90   
1         1    A  151315 2011-11-18        62.25       3.308    6074.12   
2         1    A  151315 2011-11-25        60.14       3.236     410.31   
3         1    A  151315 2011-12-02        48.91       3.172    5629.51   
4         1    A  151315 2011-12-09        43.93       3.158    4640.65   
...     ...  ...     ...        ...          ...         ...        ...   
4045     45    B  118221 2013-06-28        76.05       3.639    4842.29   
4046     45    B  118221 2013-07-05        77.50       3.614    9090.48   
4047     45    B  118221 2013-07-12        79.37       3.614    3789.94   
4048     45    B  118221 2013-07-19        82.84       3.737    2961.49   
4049     45    B  118221 2013-07-26        76.06       3.804     212.02   

      MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  \
0       6115.67     215.07    2406.62    6551.42  217.998085         7.866   
1        254.39      51.98     427.39    5988.57  218.220509         7.866   
2         98.00   55805.51       8.00     554.92  218.467621         7.866   
3         68.00    1398.11    2084.64   20475.32  218.714733         7.866   
4         19.00     105.02    3639.42   14461.82  218.961846         7.866   
...         ...        ...        ...        ...         ...           ...   
4045     975.03       3.00    2449.97    3169.69         NaN           NaN   
4046    2268.58     582.74    5797.47    1514.93         NaN           NaN   
4047    1827.31      85.72     744.84    2150.36         NaN           NaN   
4048    1047.07     204.19     363.00    1059.46         NaN           NaN   
4049     851.73       2.06      10.88    1864.57         NaN           NaN   

         IsHoliday  Week_Number  
0       No Holiday           45  
1       No Holiday           46  
2     Thanksgiving           47  
3       No Holiday           48  
4       No Holiday           49  
...            ...          ...  
4045    No Holiday           26  
4046    No Holiday           27  
4047    No Holiday           28  
4048    No Holiday           29  
4049    No Holiday           30  

[4050 rows x 15 columns]

In [100]:
# dataframe with all the cpi and unemployment values are null

cpi_unemp_null = markdown_notnull[(markdown_notnull.CPI.isna()==True) & (markdown_notnull.Unemployment.isna()==True)]
cpi_unemp_null

Store Type    Size       Date  Temperature  Fuel_Price  MarkDown1  \
77        1    A  151315 2013-05-03        66.66       3.386    2298.63   
78        1    A  151315 2013-05-10        63.90       3.392    4624.61   
79        1    A  151315 2013-05-17        69.53       3.454   16170.50   
80        1    A  151315 2013-05-24        77.19       3.494    7959.89   
81        1    A  151315 2013-05-31        78.02       3.466    2369.77   
...     ...  ...     ...        ...          ...         ...        ...   
4045     45    B  118221 2013-06-28        76.05       3.639    4842.29   
4046     45    B  118221 2013-07-05        77.50       3.614    9090.48   
4047     45    B  118221 2013-07-12        79.37       3.614    3789.94   
4048     45    B  118221 2013-07-19        82.84       3.737    2961.49   
4049     45    B  118221 2013-07-26        76.06       3.804     212.02   

      MarkDown2  MarkDown3  MarkDown4  MarkDown5  CPI  Unemployment  \
77         2.00     129.90      55.46    1301.04  NaN           NaN   
78        83.88      42.38    1618.31    8144.90  NaN           NaN   
79        92.00       8.32    4127.24    6206.97  NaN           NaN   
80       178.00    1621.47    3152.57    2938.70  NaN           NaN   
81       142.45     475.35      45.55    2056.84  NaN           NaN   
...         ...        ...        ...        ...  ...           ...   
4045     975.03       3.00    2449.97    3169.69  NaN           NaN   
4046    2268.58     582.74    5797.47    1514.93  NaN           NaN   
4047    1827.31      85.72     744.84    2150.36  NaN           NaN   
4048    1047.07     204.19     363.00    1059.46  NaN           NaN   
4049     851.73       2.06      10.88    1864.57  NaN           NaN   

       IsHoliday  Week_Number  
77    No Holiday           18  
78    No Holiday           19  
79    No Holiday           20  
80    No Holiday           21  
81    No Holiday           22  
...          ...          ...  
4045  No Holiday           26  
4046  No Holiday           27  
4047  No Holiday           28  
4048  No Holiday           29  
4049  No Holiday           30  

[585 rows x 15 columns]

In [101]:
print('Null values : ', { column: cpi_unemp_null[column].isna().sum() for column in ['CPI', 'Unemployment']})

Null values :  {'CPI': 585, 'Unemployment': 585}


Both cpi and unemployment commonly has 585 null values (markdown_null dataframe)

Above data with all null values is present until 26-07-2013

Hence cpi and unemp. data is not available only after 03-05-2013

In [109]:
# splitting to separate dataframes with the date as null and not null

# all the cpi and unemp. values are null
cpi_unemp_null = markdown_notnull[markdown_notnull.Date >= '2013-05-03']
cpi_unemp_null.reset_index(drop = True, inplace = True)

#random null values in markdown
cpi_unemp_notnull = markdown_notnull[markdown_notnull.Date < '2013-05-03']
cpi_unemp_notnull.reset_index(drop = True, inplace = True)

In [110]:
cpi_unemp_null

Store Type    Size       Date  Temperature  Fuel_Price  MarkDown1  \
0        1    A  151315 2013-05-03        66.66       3.386    2298.63   
1        1    A  151315 2013-05-10        63.90       3.392    4624.61   
2        1    A  151315 2013-05-17        69.53       3.454   16170.50   
3        1    A  151315 2013-05-24        77.19       3.494    7959.89   
4        1    A  151315 2013-05-31        78.02       3.466    2369.77   
..     ...  ...     ...        ...          ...         ...        ...   
580     45    B  118221 2013-06-28        76.05       3.639    4842.29   
581     45    B  118221 2013-07-05        77.50       3.614    9090.48   
582     45    B  118221 2013-07-12        79.37       3.614    3789.94   
583     45    B  118221 2013-07-19        82.84       3.737    2961.49   
584     45    B  118221 2013-07-26        76.06       3.804     212.02   

     MarkDown2  MarkDown3  MarkDown4  MarkDown5  CPI  Unemployment  \
0         2.00     129.90      55.46    1301.04  NaN           NaN   
1        83.88      42.38    1618.31    8144.90  NaN           NaN   
2        92.00       8.32    4127.24    6206.97  NaN           NaN   
3       178.00    1621.47    3152.57    2938.70  NaN           NaN   
4       142.45     475.35      45.55    2056.84  NaN           NaN   
..         ...        ...        ...        ...  ...           ...   
580     975.03       3.00    2449.97    3169.69  NaN           NaN   
581    2268.58     582.74    5797.47    1514.93  NaN           NaN   
582    1827.31      85.72     744.84    2150.36  NaN           NaN   
583    1047.07     204.19     363.00    1059.46  NaN           NaN   
584     851.73       2.06      10.88    1864.57  NaN           NaN   

      IsHoliday  Week_Number  
0    No Holiday           18  
1    No Holiday           19  
2    No Holiday           20  
3    No Holiday           21  
4    No Holiday           22  
..          ...          ...  
580  No Holiday           26  
581  No Holiday           27  
582  No Holiday           28  
583  No Holiday           29  
584  No Holiday           30  

[585 rows x 15 columns]

In [111]:
cpi_unemp_notnull

Store Type    Size       Date  Temperature  Fuel_Price  MarkDown1  \
0         1    A  151315 2011-11-11        59.11       3.297   10382.90   
1         1    A  151315 2011-11-18        62.25       3.308    6074.12   
2         1    A  151315 2011-11-25        60.14       3.236     410.31   
3         1    A  151315 2011-12-02        48.91       3.172    5629.51   
4         1    A  151315 2011-12-09        43.93       3.158    4640.65   
...     ...  ...     ...        ...          ...         ...        ...   
3460     45    B  118221 2013-03-29        40.68       3.784    5444.00   
3461     45    B  118221 2013-04-05        43.94       3.763   16427.83   
3462     45    B  118221 2013-04-12        57.39       3.724    8760.15   
3463     45    B  118221 2013-04-19        56.27       3.676    1399.81   
3464     45    B  118221 2013-04-26        50.64       3.615    1260.65   

      MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  \
0       6115.67     215.07    2406.62    6551.42  217.998085         7.866   
1        254.39      51.98     427.39    5988.57  218.220509         7.866   
2         98.00   55805.51       8.00     554.92  218.467621         7.866   
3         68.00    1398.11    2084.64   20475.32  218.714733         7.866   
4         19.00     105.02    3639.42   14461.82  218.961846         7.866   
...         ...        ...        ...        ...         ...           ...   
3460       0.00     350.84      53.90    1722.11  193.442790         8.625   
3461    5341.41     182.59    1523.83    1743.09  193.516047         8.335   
3462    1713.11      21.08    1302.31    1380.74  193.589304         8.335   
3463      39.89      44.38      60.83    1445.05  193.589304         8.335   
3464       0.00      57.52      40.51    2476.18  193.589304         8.335   

         IsHoliday  Week_Number  
0       No Holiday           45  
1       No Holiday           46  
2     Thanksgiving           47  
3       No Holiday           48  
4       No Holiday           49  
...            ...          ...  
3460    No Holiday           13  
3461    No Holiday           14  
3462    No Holiday           15  
3463    No Holiday           16  
3464    No Holiday           17  

[3465 rows x 15 columns]

In [112]:
# cross checking the dataframes - cpi_unemp_null dataframe

print('Null values : ', { column: cpi_unemp_null[column].isna().sum() for column in ['CPI', 'Unemployment']})

Null values :  {'CPI': 585, 'Unemployment': 585}


In [113]:
# cpi_unemp_notnull dataframe

print('Null values : ', { column: cpi_unemp_notnull[column].isna().sum() for column in ['CPI', 'Unemployment']})

Null values :  {'CPI': 0, 'Unemployment': 0}


#### Missing values in CPI & Unemployment Columns

In [114]:
df_cpi_unemp_notnull = cpi_unemp_notnull.copy()

#splitting the date to separate columns
df_cpi_unemp_notnull['Day'] = df_cpi_unemp_notnull['Date'].dt.day
df_cpi_unemp_notnull['Month'] = df_cpi_unemp_notnull['Date'].dt.month
df_cpi_unemp_notnull['Year'] = df_cpi_unemp_notnull['Date'].dt.year

df_cpi_unemp_notnull.drop('Date', axis = True, inplace = True)
df_cpi_unemp_notnull

Store Type    Size  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
0         1    A  151315        59.11       3.297   10382.90    6115.67   
1         1    A  151315        62.25       3.308    6074.12     254.39   
2         1    A  151315        60.14       3.236     410.31      98.00   
3         1    A  151315        48.91       3.172    5629.51      68.00   
4         1    A  151315        43.93       3.158    4640.65      19.00   
...     ...  ...     ...          ...         ...        ...        ...   
3460     45    B  118221        40.68       3.784    5444.00       0.00   
3461     45    B  118221        43.94       3.763   16427.83    5341.41   
3462     45    B  118221        57.39       3.724    8760.15    1713.11   
3463     45    B  118221        56.27       3.676    1399.81      39.89   
3464     45    B  118221        50.64       3.615    1260.65       0.00   

      MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment     IsHoliday  \
0        215.07    2406.62    6551.42  217.998085         7.866    No Holiday   
1         51.98     427.39    5988.57  218.220509         7.866    No Holiday   
2      55805.51       8.00     554.92  218.467621         7.866  Thanksgiving   
3       1398.11    2084.64   20475.32  218.714733         7.866    No Holiday   
4        105.02    3639.42   14461.82  218.961846         7.866    No Holiday   
...         ...        ...        ...         ...           ...           ...   
3460     350.84      53.90    1722.11  193.442790         8.625    No Holiday   
3461     182.59    1523.83    1743.09  193.516047         8.335    No Holiday   
3462      21.08    1302.31    1380.74  193.589304         8.335    No Holiday   
3463      44.38      60.83    1445.05  193.589304         8.335    No Holiday   
3464      57.52      40.51    2476.18  193.589304         8.335    No Holiday   

      Week_Number  Day  Month  Year  
0              45   11     11  2011  
1              46   18     11  2011  
2              47   25     11  2011  
3              48    2     12  2011  
4              49    9     12  2011  
...           ...  ...    ...   ...  
3460           13   29      3  2013  
3461           14    5      4  2013  
3462           15   12      4  2013  
3463           16   19      4  2013  
3464           17   26      4  2013  

[3465 rows x 17 columns]

In [115]:
df_cpi_unemp_null = cpi_unemp_null.copy()

#splitting the date to separate columns
df_cpi_unemp_null['Day'] = df_cpi_unemp_null['Date'].dt.day
df_cpi_unemp_null['Month'] = df_cpi_unemp_null['Date'].dt.month
df_cpi_unemp_null['Year'] = df_cpi_unemp_null['Date'].dt.year

df_cpi_unemp_null.drop('Date', axis = True, inplace = True)
df_cpi_unemp_null

Store Type    Size  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
0        1    A  151315        66.66       3.386    2298.63       2.00   
1        1    A  151315        63.90       3.392    4624.61      83.88   
2        1    A  151315        69.53       3.454   16170.50      92.00   
3        1    A  151315        77.19       3.494    7959.89     178.00   
4        1    A  151315        78.02       3.466    2369.77     142.45   
..     ...  ...     ...          ...         ...        ...        ...   
580     45    B  118221        76.05       3.639    4842.29     975.03   
581     45    B  118221        77.50       3.614    9090.48    2268.58   
582     45    B  118221        79.37       3.614    3789.94    1827.31   
583     45    B  118221        82.84       3.737    2961.49    1047.07   
584     45    B  118221        76.06       3.804     212.02     851.73   

     MarkDown3  MarkDown4  MarkDown5  CPI  Unemployment   IsHoliday  \
0       129.90      55.46    1301.04  NaN           NaN  No Holiday   
1        42.38    1618.31    8144.90  NaN           NaN  No Holiday   
2         8.32    4127.24    6206.97  NaN           NaN  No Holiday   
3      1621.47    3152.57    2938.70  NaN           NaN  No Holiday   
4       475.35      45.55    2056.84  NaN           NaN  No Holiday   
..         ...        ...        ...  ...           ...         ...   
580       3.00    2449.97    3169.69  NaN           NaN  No Holiday   
581     582.74    5797.47    1514.93  NaN           NaN  No Holiday   
582      85.72     744.84    2150.36  NaN           NaN  No Holiday   
583     204.19     363.00    1059.46  NaN           NaN  No Holiday   
584       2.06      10.88    1864.57  NaN           NaN  No Holiday   

     Week_Number  Day  Month  Year  
0             18    3      5  2013  
1             19   10      5  2013  
2             20   17      5  2013  
3             21   24      5  2013  
4             22   31      5  2013  
..           ...  ...    ...   ...  
580           26   28      6  2013  
581           27    5      7  2013  
582           28   12      7  2013  
583           29   19      7  2013  
584           30   26      7  2013  

[585 rows x 17 columns]

Building a model to predict the cpi & unemployment values to fill the missing values

In [116]:
# converting categorical data into numerical values for model training

holiday = {'No Holiday': 0,
           'Super Bowl': 1,
           'Labor Day': 2,
           'Thanksgiving': 3,
           'Christmas': 4}

for_type = {'A': 1,
            'B': 2,
            'C': 3}

df_cpi_unemp_notnull['IsHoliday'] = df_cpi_unemp_notnull['IsHoliday'].map(holiday)
df_cpi_unemp_notnull['Type'] = df_cpi_unemp_notnull['Type'].map(for_type)

df_cpi_unemp_null['IsHoliday'] = df_cpi_unemp_null['IsHoliday'].map(holiday)
df_cpi_unemp_null['Type'] = df_cpi_unemp_null['Type'].map(for_type)

In [117]:
df_cpi_unemp_notnull.dtypes

Store             int64
Type              int64
Size              int64
Temperature     float64
Fuel_Price      float64
MarkDown1       float64
MarkDown2       float64
MarkDown3       float64
MarkDown4       float64
MarkDown5       float64
CPI             float64
Unemployment    float64
IsHoliday         int64
Week_Number      UInt32
Day               int32
Month             int32
Year              int32
dtype: object

In [119]:
# importing the algorithms

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from xgboost import XGBRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.linear_model import LinearRegression

Training the model to predict Unemployment

In [120]:
x = df_cpi_unemp_notnull.drop(['CPI', 'Unemployment'], axis = 1)
y = df_cpi_unemp_notnull['Unemployment']

In [121]:
# Splitting the data for train test

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 42)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(2772, 15) (693, 15) (2772,) (693,)


In [125]:
# Function to Compare the metrics for all of the models

models = [('XGB Regressor', XGBRegressor()),
          ('Decision Tree Regressor', DecisionTreeRegressor()),
          ('AdaBoost Regressor' ,AdaBoostRegressor()),
          ('Extra Trees  Regressor', ExtraTreesRegressor()),
          ('Random Forest Regressor', RandomForestRegressor()),
          ('Gradient Boosting Regressor', GradientBoostingRegressor()),
          ('HistGradient Boosting Regressor', HistGradientBoostingRegressor()),
          ('Linear Regression', LinearRegression())
          ]

result = []

def ml_regression():

    for model_name, model in models:

        model.fit(x_train, y_train)
        y_train_pred = model.predict(x_train)
        y_test_pred = model.predict(x_test)

        metrics = {'Model name': model_name,
                   'Train_mse': round(mean_squared_error(y_train, y_train_pred), 4),
                   'Test_mse': round(mean_squared_error(y_test, y_test_pred), 4),
                   'Train_mae': round(mean_absolute_error(y_train, y_train_pred), 4),
                   'Test_mae': round(mean_absolute_error(y_test, y_test_pred), 4),
                   'Train_R2_score': round(r2_score(y_train, y_train_pred), 4),
                   'Test_R2_score': round(r2_score(y_test, y_test_pred), 4)}
        result.append(metrics)

    score_df = pd.DataFrame(result)

    return(score_df)

In [126]:
ml_regression()

Model name  Train_mse  Test_mse  Train_mae  Test_mae  \
0                    XGB Regressor     0.0008    0.0230     0.0206    0.0955   
1          Decision Tree Regressor     0.0000    0.0673     0.0000    0.0433   
2               AdaBoost Regressor     1.4638    1.5744     1.0541    1.0915   
3           Extra Trees  Regressor     0.0000    0.0323     0.0000    0.1096   
4          Random Forest Regressor     0.0033    0.0171     0.0306    0.0734   
5      Gradient Boosting Regressor     0.1670    0.1893     0.3179    0.3358   
6  HistGradient Boosting Regressor     0.0098    0.0206     0.0695    0.0962   
7                Linear Regression     2.2794    2.2849     1.1210    1.1327   

   Train_R2_score  Test_R2_score  
0          0.9997         0.9920  
1          1.0000         0.9765  
2          0.4902         0.4511  
3          1.0000         0.9887  
4          0.9989         0.9941  
5          0.9418         0.9340  
6          0.9966         0.9928  
7          0.2061         0.2035

Choosing Hist Gradient boosting regressor because they're capable of capturing complex patterns in the data.

In [127]:
unemp_model = HistGradientBoostingRegressor().fit(x,y)
y_pred = unemp_model.predict(x)
mean_squared_error(y, y_pred)

0.009042423539192131

In [129]:
# predicting for the null dataframe

x_new = df_cpi_unemp_null.drop(['CPI', 'Unemployment'], axis = 1)
predicted_unemp = unemp_model.predict(x_new)

In [130]:
# filling the null values of unemployment with the predicted value

df_cpi_unemp_null['Unemployment'] = predicted_unemp
df_cpi_unemp_null

Store  Type    Size  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
0        1     1  151315        66.66       3.386    2298.63       2.00   
1        1     1  151315        63.90       3.392    4624.61      83.88   
2        1     1  151315        69.53       3.454   16170.50      92.00   
3        1     1  151315        77.19       3.494    7959.89     178.00   
4        1     1  151315        78.02       3.466    2369.77     142.45   
..     ...   ...     ...          ...         ...        ...        ...   
580     45     2  118221        76.05       3.639    4842.29     975.03   
581     45     2  118221        77.50       3.614    9090.48    2268.58   
582     45     2  118221        79.37       3.614    3789.94    1827.31   
583     45     2  118221        82.84       3.737    2961.49    1047.07   
584     45     2  118221        76.06       3.804     212.02     851.73   

     MarkDown3  MarkDown4  MarkDown5  CPI  Unemployment  IsHoliday  \
0       129.90      55.46    1301.04  NaN      6.406919          0   
1        42.38    1618.31    8144.90  NaN      6.390168          0   
2         8.32    4127.24    6206.97  NaN      6.414178          0   
3      1621.47    3152.57    2938.70  NaN      6.411540          0   
4       475.35      45.55    2056.84  NaN      6.451834          0   
..         ...        ...        ...  ...           ...        ...   
580       3.00    2449.97    3169.69  NaN      8.308551          0   
581     582.74    5797.47    1514.93  NaN      8.249614          0   
582      85.72     744.84    2150.36  NaN      8.287728          0   
583     204.19     363.00    1059.46  NaN      8.581907          0   
584       2.06      10.88    1864.57  NaN      8.590008          0   

     Week_Number  Day  Month  Year  
0             18    3      5  2013  
1             19   10      5  2013  
2             20   17      5  2013  
3             21   24      5  2013  
4             22   31      5  2013  
..           ...  ...    ...   ...  
580           26   28      6  2013  
581           27    5      7  2013  
582           28   12      7  2013  
583           29   19      7  2013  
584           30   26      7  2013  

[585 rows x 17 columns]

Training the model to predict CPI

In [142]:
x1 = df_cpi_unemp_notnull.drop(['CPI'], axis = 1)
y1 = df_cpi_unemp_notnull['CPI']

In [143]:
# Splitting the data for train test

x_train, x_test, y_train, y_test = train_test_split(x1, y1, test_size= 0.2, random_state= 42)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(2772, 16) (693, 16) (2772,) (693,)


In [144]:
result_1 = []

def ml_regression_1():

    for model_name, model in models:

        model.fit(x_train, y_train)
        y_train_pred = model.predict(x_train)
        y_test_pred = model.predict(x_test)

        metrics = {'Model name': model_name,
                   'Train_mse': round(mean_squared_error(y_train, y_train_pred), 4),
                   'Test_mse': round(mean_squared_error(y_test, y_test_pred), 4),
                   'Train_mae': round(mean_absolute_error(y_train, y_train_pred), 4),
                   'Test_mae': round(mean_absolute_error(y_test, y_test_pred), 4),
                   'Train_R2_score': round(r2_score(y_train, y_train_pred), 4),
                   'Test_R2_score': round(r2_score(y_test, y_test_pred), 4)}
        result_1.append(metrics)

    score_df = pd.DataFrame(result_1)

    return(score_df)

In [145]:
ml_regression_1()

Model name  Train_mse   Test_mse  Train_mae  Test_mae  \
0                    XGB Regressor     0.1428     3.3579     0.2614    1.1343   
1          Decision Tree Regressor     0.0000     2.6441     0.0000    0.2331   
2               AdaBoost Regressor   542.2087   538.1648    21.0768   20.9127   
3           Extra Trees  Regressor     0.0000     4.0611     0.0000    1.1268   
4          Random Forest Regressor     1.9133     7.5216     0.3953    0.8839   
5      Gradient Boosting Regressor    52.8662    50.5778     5.3613    5.3598   
6  HistGradient Boosting Regressor     0.7521     2.9595     0.5061    0.7823   
7                Linear Regression  1136.7365  1138.3789    28.6578   28.4127   

   Train_R2_score  Test_R2_score  
0          0.9999         0.9980  
1          1.0000         0.9984  
2          0.6741         0.6822  
3          1.0000         0.9976  
4          0.9988         0.9956  
5          0.9682         0.9701  
6          0.9995         0.9983  
7          0.3167         0.3277

In [147]:
cpi_model = HistGradientBoostingRegressor().fit(x1, y1)
y_pred = cpi_model.predict(x1)
mean_squared_error(y1, y_pred)

1.4193234352769577

In [148]:
# predicting for the null dataframe

x_new = df_cpi_unemp_null.drop(['CPI'], axis = 1)
predicted_cpi = cpi_model.predict(x_new)

In [149]:
# filling the null values of CPI with the predicted value

df_cpi_unemp_null['CPI'] = predicted_cpi
df_cpi_unemp_null

Store  Type    Size  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
0        1     1  151315        66.66       3.386    2298.63       2.00   
1        1     1  151315        63.90       3.392    4624.61      83.88   
2        1     1  151315        69.53       3.454   16170.50      92.00   
3        1     1  151315        77.19       3.494    7959.89     178.00   
4        1     1  151315        78.02       3.466    2369.77     142.45   
..     ...   ...     ...          ...         ...        ...        ...   
580     45     2  118221        76.05       3.639    4842.29     975.03   
581     45     2  118221        77.50       3.614    9090.48    2268.58   
582     45     2  118221        79.37       3.614    3789.94    1827.31   
583     45     2  118221        82.84       3.737    2961.49    1047.07   
584     45     2  118221        76.06       3.804     212.02     851.73   

     MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
0       129.90      55.46    1301.04  223.977274      6.406919          0   
1        42.38    1618.31    8144.90  224.044858      6.390168          0   
2         8.32    4127.24    6206.97  224.164856      6.414178          0   
3      1621.47    3152.57    2938.70  223.706061      6.411540          0   
4       475.35      45.55    2056.84  223.856900      6.451834          0   
..         ...        ...        ...         ...           ...        ...   
580       3.00    2449.97    3169.69  192.825518      8.308551          0   
581     582.74    5797.47    1514.93  192.615082      8.249614          0   
582      85.72     744.84    2150.36  192.803314      8.287728          0   
583     204.19     363.00    1059.46  192.748473      8.581907          0   
584       2.06      10.88    1864.57  193.491386      8.590008          0   

     Week_Number  Day  Month  Year  
0             18    3      5  2013  
1             19   10      5  2013  
2             20   17      5  2013  
3             21   24      5  2013  
4             22   31      5  2013  
..           ...  ...    ...   ...  
580           26   28      6  2013  
581           27    5      7  2013  
582           28   12      7  2013  
583           29   19      7  2013  
584           30   26      7  2013  

[585 rows x 17 columns]

In [150]:
# concat both cpi dataframe to single dataframe which has no null values

df_markdown_notnull = pd.concat([df_cpi_unemp_notnull, df_cpi_unemp_null], ignore_index = True)
df_markdown_notnull

Store  Type    Size  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
0         1     1  151315        59.11       3.297   10382.90    6115.67   
1         1     1  151315        62.25       3.308    6074.12     254.39   
2         1     1  151315        60.14       3.236     410.31      98.00   
3         1     1  151315        48.91       3.172    5629.51      68.00   
4         1     1  151315        43.93       3.158    4640.65      19.00   
...     ...   ...     ...          ...         ...        ...        ...   
4045     45     2  118221        76.05       3.639    4842.29     975.03   
4046     45     2  118221        77.50       3.614    9090.48    2268.58   
4047     45     2  118221        79.37       3.614    3789.94    1827.31   
4048     45     2  118221        82.84       3.737    2961.49    1047.07   
4049     45     2  118221        76.06       3.804     212.02     851.73   

      MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
0        215.07    2406.62    6551.42  217.998085      7.866000          0   
1         51.98     427.39    5988.57  218.220509      7.866000          0   
2      55805.51       8.00     554.92  218.467621      7.866000          3   
3       1398.11    2084.64   20475.32  218.714733      7.866000          0   
4        105.02    3639.42   14461.82  218.961846      7.866000          0   
...         ...        ...        ...         ...           ...        ...   
4045       3.00    2449.97    3169.69  192.825518      8.308551          0   
4046     582.74    5797.47    1514.93  192.615082      8.249614          0   
4047      85.72     744.84    2150.36  192.803314      8.287728          0   
4048     204.19     363.00    1059.46  192.748473      8.581907          0   
4049       2.06      10.88    1864.57  193.491386      8.590008          0   

      Week_Number  Day  Month  Year  
0              45   11     11  2011  
1              46   18     11  2011  
2              47   25     11  2011  
3              48    2     12  2011  
4              49    9     12  2011  
...           ...  ...    ...   ...  
4045           26   28      6  2013  
4046           27    5      7  2013  
4047           28   12      7  2013  
4048           29   19      7  2013  
4049           30   26      7  2013  

[4050 rows x 17 columns]

## Missing values in Markdown

In [151]:
markdown_null

Store Type    Size       Date  Temperature  Fuel_Price  MarkDown1  \
0         1    A  151315 2010-02-05        42.31       2.572        NaN   
1         1    A  151315 2010-02-12        38.51       2.548        NaN   
2         1    A  151315 2010-02-19        39.93       2.514        NaN   
3         1    A  151315 2010-02-26        46.63       2.561        NaN   
4         1    A  151315 2010-03-05        46.50       2.625        NaN   
...     ...  ...     ...        ...          ...         ...        ...   
4135     45    B  118221 2011-10-07        55.82       3.583        NaN   
4136     45    B  118221 2011-10-14        63.82       3.541        NaN   
4137     45    B  118221 2011-10-21        59.60       3.570        NaN   
4138     45    B  118221 2011-10-28        51.78       3.569        NaN   
4139     45    B  118221 2011-11-04        43.92       3.551        NaN   

      MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  \
0           NaN        NaN        NaN        NaN  211.096358         8.106   
1           NaN        NaN        NaN        NaN  211.242170         8.106   
2           NaN        NaN        NaN        NaN  211.289143         8.106   
3           NaN        NaN        NaN        NaN  211.319643         8.106   
4           NaN        NaN        NaN        NaN  211.350143         8.106   
...         ...        ...        ...        ...         ...           ...   
4135        NaN        NaN        NaN        NaN  187.483796         8.523   
4136        NaN        NaN        NaN        NaN  187.691748         8.523   
4137        NaN        NaN        NaN        NaN  187.784620         8.523   
4138        NaN        NaN        NaN        NaN  187.877491         8.523   
4139        NaN        NaN        NaN        NaN  187.970363         8.523   

       IsHoliday  Week_Number  
0     No Holiday            5  
1     Super Bowl            6  
2     No Holiday            7  
3     No Holiday            8  
4     No Holiday            9  
...          ...          ...  
4135  No Holiday           40  
4136  No Holiday           41  
4137  No Holiday           42  
4138  No Holiday           43  
4139  No Holiday           44  

[4140 rows x 15 columns]

In [154]:
df_markdown_null = markdown_null.copy()

#splitting the date to separate columns
df_markdown_null['Day'] = df_markdown_null['Date'].dt.day
df_markdown_null['Month'] = df_markdown_null['Date'].dt.month
df_markdown_null['Year'] = df_markdown_null['Date'].dt.year

df_markdown_null.drop('Date', axis = True, inplace = True)
df_markdown_null

Store Type    Size  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
0         1    A  151315        42.31       2.572        NaN        NaN   
1         1    A  151315        38.51       2.548        NaN        NaN   
2         1    A  151315        39.93       2.514        NaN        NaN   
3         1    A  151315        46.63       2.561        NaN        NaN   
4         1    A  151315        46.50       2.625        NaN        NaN   
...     ...  ...     ...          ...         ...        ...        ...   
4135     45    B  118221        55.82       3.583        NaN        NaN   
4136     45    B  118221        63.82       3.541        NaN        NaN   
4137     45    B  118221        59.60       3.570        NaN        NaN   
4138     45    B  118221        51.78       3.569        NaN        NaN   
4139     45    B  118221        43.92       3.551        NaN        NaN   

      MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment   IsHoliday  \
0           NaN        NaN        NaN  211.096358         8.106  No Holiday   
1           NaN        NaN        NaN  211.242170         8.106  Super Bowl   
2           NaN        NaN        NaN  211.289143         8.106  No Holiday   
3           NaN        NaN        NaN  211.319643         8.106  No Holiday   
4           NaN        NaN        NaN  211.350143         8.106  No Holiday   
...         ...        ...        ...         ...           ...         ...   
4135        NaN        NaN        NaN  187.483796         8.523  No Holiday   
4136        NaN        NaN        NaN  187.691748         8.523  No Holiday   
4137        NaN        NaN        NaN  187.784620         8.523  No Holiday   
4138        NaN        NaN        NaN  187.877491         8.523  No Holiday   
4139        NaN        NaN        NaN  187.970363         8.523  No Holiday   

      Week_Number  Day  Month  Year  
0               5    5      2  2010  
1               6   12      2  2010  
2               7   19      2  2010  
3               8   26      2  2010  
4               9    5      3  2010  
...           ...  ...    ...   ...  
4135           40    7     10  2011  
4136           41   14     10  2011  
4137           42   21     10  2011  
4138           43   28     10  2011  
4139           44    4     11  2011  

[4140 rows x 17 columns]

In [155]:
# converting categorical data into numerical values for model training

holiday = {'No Holiday': 0,
           'Super Bowl': 1,
           'Labor Day': 2,
           'Thanksgiving': 3,
           'Christmas': 4}

for_type = {'A': 1,
            'B': 2,
            'C': 3}

df_markdown_null['IsHoliday'] = df_markdown_null['IsHoliday'].map(holiday)
df_markdown_null['Type'] = df_markdown_null['Type'].map(for_type)

df_markdown_null.head()

Store  Type    Size  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
0      1     1  151315        42.31       2.572        NaN        NaN   
1      1     1  151315        38.51       2.548        NaN        NaN   
2      1     1  151315        39.93       2.514        NaN        NaN   
3      1     1  151315        46.63       2.561        NaN        NaN   
4      1     1  151315        46.50       2.625        NaN        NaN   

   MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
0        NaN        NaN        NaN  211.096358         8.106          0   
1        NaN        NaN        NaN  211.242170         8.106          1   
2        NaN        NaN        NaN  211.289143         8.106          0   
3        NaN        NaN        NaN  211.319643         8.106          0   
4        NaN        NaN        NaN  211.350143         8.106          0   

   Week_Number  Day  Month  Year  
0            5    5      2  2010  
1            6   12      2  2010  
2            7   19      2  2010  
3            8   26      2  2010  
4            9    5      3  2010

Training the model to predict the markdown values

In [156]:
result_2 = []

def ml_regression_2():

    for model_name, model in models:

        model.fit(x_train, y_train)
        y_train_pred = model.predict(x_train)
        y_test_pred = model.predict(x_test)

        metrics = {'Model name': model_name,
                   'Train_mse': round(mean_squared_error(y_train, y_train_pred), 4),
                   'Test_mse': round(mean_squared_error(y_test, y_test_pred), 4),
                   'Train_mae': round(mean_absolute_error(y_train, y_train_pred), 4),
                   'Test_mae': round(mean_absolute_error(y_test, y_test_pred), 4),
                   'Train_R2_score': round(r2_score(y_train, y_train_pred), 4),
                   'Test_R2_score': round(r2_score(y_test, y_test_pred), 4)}
        result_2.append(metrics)

    score_df = pd.DataFrame(result_2)

    return(score_df)

In [158]:
x2 = df_markdown_notnull.drop(['MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5'], axis = 1)
y2 = df_markdown_notnull['MarkDown1']

In [159]:
# Splitting the data for train test

x_train, x_test, y_train, y_test = train_test_split(x2, y2, test_size = 0.2, random_state = 42)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(3240, 12) (810, 12) (3240,) (810,)


In [160]:
ml_regression_2()

Model name     Train_mse      Test_mse  Train_mae  \
0                    XGB Regressor  1.193367e+06  1.975853e+07   738.3113   
1          Decision Tree Regressor  0.000000e+00  5.210850e+07     0.0000   
2               AdaBoost Regressor  9.921778e+07  1.075684e+08  8903.3401   
3           Extra Trees  Regressor  0.000000e+00  2.146868e+07     0.0000   
4          Random Forest Regressor  3.610782e+06  2.175730e+07   976.9948   
5      Gradient Boosting Regressor  2.226315e+07  2.264795e+07  2680.1197   
6  HistGradient Boosting Regressor  8.745250e+06  1.798979e+07  1706.0225   
7                Linear Regression  6.534021e+07  5.272841e+07  4670.4662   

    Test_mae  Train_R2_score  Test_R2_score  
0  2806.6136          0.9866         0.7241  
1  3854.4729          1.0000         0.2724  
2  9177.5354         -0.1134        -0.5020  
3  2750.7669          1.0000         0.7002  
4  2847.9339          0.9595         0.6962  
5  3010.0418          0.7502         0.6838  
6  2651.8116          0.9019         0.7488  
7  4531.5544          0.2668         0.2637

Choosing Random Forest algorithm, due to its good interpretability in parallel processing

In [163]:
model = RandomForestRegressor().fit(x2, y2)
y_pred = model.predict(x2)
print(mean_absolute_error(y2, y_pred))

957.8873400740738


In [168]:
# Model for MarkDown 1

x = df_markdown_notnull.drop(['MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5'], axis = 1)
y = df_markdown_notnull['MarkDown1']

markdown_model_1 = RandomForestRegressor().fit(x, y)
y_pred = markdown_model_1.predict(x)
print(mean_absolute_error(y, y_pred))

# applying the model for null dataframe

x_new = df_markdown_null.drop(['MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5'], axis = 1)
predicted_markdown_1 = markdown_model_1.predict(x_new)

# Inserting the predicted markdown1 values into the null dataframe

df_markdown_null['MarkDown1'] = predicted_markdown_1
df_markdown_null

962.867240148148


Store  Type    Size  Temperature  Fuel_Price   MarkDown1  MarkDown2  \
0         1     1  151315        42.31       2.572  20522.5677        NaN   
1         1     1  151315        38.51       2.548  24408.0508        NaN   
2         1     1  151315        39.93       2.514  17676.8263        NaN   
3         1     1  151315        46.63       2.561  11852.7496        NaN   
4         1     1  151315        46.50       2.625  17209.1016        NaN   
...     ...   ...     ...          ...         ...         ...        ...   
4135     45     2  118221        55.82       3.583   7352.9472        NaN   
4136     45     2  118221        63.82       3.541   6127.8563        NaN   
4137     45     2  118221        59.60       3.570   3292.7920        NaN   
4138     45     2  118221        51.78       3.569   3711.9116        NaN   
4139     45     2  118221        43.92       3.551   6649.4411        NaN   

      MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
0           NaN        NaN        NaN  211.096358         8.106          0   
1           NaN        NaN        NaN  211.242170         8.106          1   
2           NaN        NaN        NaN  211.289143         8.106          0   
3           NaN        NaN        NaN  211.319643         8.106          0   
4           NaN        NaN        NaN  211.350143         8.106          0   
...         ...        ...        ...         ...           ...        ...   
4135        NaN        NaN        NaN  187.483796         8.523          0   
4136        NaN        NaN        NaN  187.691748         8.523          0   
4137        NaN        NaN        NaN  187.784620         8.523          0   
4138        NaN        NaN        NaN  187.877491         8.523          0   
4139        NaN        NaN        NaN  187.970363         8.523          0   

      Week_Number  Day  Month  Year  
0               5    5      2  2010  
1               6   12      2  2010  
2               7   19      2  2010  
3               8   26      2  2010  
4               9    5      3  2010  
...           ...  ...    ...   ...  
4135           40    7     10  2011  
4136           41   14     10  2011  
4137           42   21     10  2011  
4138           43   28     10  2011  
4139           44    4     11  2011  

[4140 rows x 17 columns]

In [169]:
# Model for MarkDown 2

x = df_markdown_notnull.drop(['MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5'], axis = 1)
y = df_markdown_notnull['MarkDown2']

markdown_model_2 = RandomForestRegressor().fit(x, y)
y_pred = markdown_model_2.predict(x)
print(mean_absolute_error(y, y_pred))

# applying the model for null dataframe

x_new = df_markdown_null.drop(['MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5'], axis = 1)
predicted_markdown_2 = markdown_model_2.predict(x_new)

# Inserting the predicted markdown1 values into the null dataframe

df_markdown_null['MarkDown2'] = predicted_markdown_2
df_markdown_null.head()

312.65698034567873


Store  Type    Size  Temperature  Fuel_Price   MarkDown1   MarkDown2  \
0      1     1  151315        42.31       2.572  20522.5677   3916.1645   
1      1     1  151315        38.51       2.548  24408.0508   5594.7194   
2      1     1  151315        39.93       2.514  17676.8263  10742.3213   
3      1     1  151315        46.63       2.561  11852.7496   9454.8240   
4      1     1  151315        46.50       2.625  17209.1016   3637.3314   

   MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
0        NaN        NaN        NaN  211.096358         8.106          0   
1        NaN        NaN        NaN  211.242170         8.106          1   
2        NaN        NaN        NaN  211.289143         8.106          0   
3        NaN        NaN        NaN  211.319643         8.106          0   
4        NaN        NaN        NaN  211.350143         8.106          0   

   Week_Number  Day  Month  Year  
0            5    5      2  2010  
1            6   12      2  2010  
2            7   19      2  2010  
3            8   26      2  2010  
4            9    5      3  2010

In [170]:
# Model for MarkDown 3

x = df_markdown_notnull.drop(['MarkDown3', 'MarkDown4', 'MarkDown5'], axis = 1)
y = df_markdown_notnull['MarkDown3']

markdown_model_3 = RandomForestRegressor().fit(x, y)
y_pred = markdown_model_3.predict(x)
print(mean_absolute_error(y, y_pred))

# applying the model for null dataframe

x_new = df_markdown_null.drop(['MarkDown3', 'MarkDown4', 'MarkDown5'], axis = 1)
predicted_markdown_3 = markdown_model_3.predict(x_new)

# Inserting the predicted markdown1 values into the null dataframe

df_markdown_null['MarkDown3'] = predicted_markdown_3
df_markdown_null.head()

162.61445370370367


Store  Type    Size  Temperature  Fuel_Price   MarkDown1   MarkDown2  \
0      1     1  151315        42.31       2.572  20522.5677   3916.1645   
1      1     1  151315        38.51       2.548  24408.0508   5594.7194   
2      1     1  151315        39.93       2.514  17676.8263  10742.3213   
3      1     1  151315        46.63       2.561  11852.7496   9454.8240   
4      1     1  151315        46.50       2.625  17209.1016   3637.3314   

   MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
0   216.3458        NaN        NaN  211.096358         8.106          0   
1   204.8776        NaN        NaN  211.242170         8.106          1   
2   311.2118        NaN        NaN  211.289143         8.106          0   
3   235.1537        NaN        NaN  211.319643         8.106          0   
4   214.4539        NaN        NaN  211.350143         8.106          0   

   Week_Number  Day  Month  Year  
0            5    5      2  2010  
1            6   12      2  2010  
2            7   19      2  2010  
3            8   26      2  2010  
4            9    5      3  2010

In [171]:
# Model for MarkDown 4

x = df_markdown_notnull.drop(['MarkDown4', 'MarkDown5'], axis = 1)
y = df_markdown_notnull['MarkDown4']

markdown_model_4 = RandomForestRegressor().fit(x, y)
y_pred = markdown_model_4.predict(x)
print(mean_absolute_error(y, y_pred))

# applying the model for null dataframe

x_new = df_markdown_null.drop(['MarkDown4', 'MarkDown5'], axis = 1)
predicted_markdown_4 = markdown_model_4.predict(x_new)

# Inserting the predicted markdown1 values into the null dataframe

df_markdown_null['MarkDown4'] = predicted_markdown_4
df_markdown_null.head()

416.5351397530867


Store  Type    Size  Temperature  Fuel_Price   MarkDown1   MarkDown2  \
0      1     1  151315        42.31       2.572  20522.5677   3916.1645   
1      1     1  151315        38.51       2.548  24408.0508   5594.7194   
2      1     1  151315        39.93       2.514  17676.8263  10742.3213   
3      1     1  151315        46.63       2.561  11852.7496   9454.8240   
4      1     1  151315        46.50       2.625  17209.1016   3637.3314   

   MarkDown3   MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
0   216.3458  19570.7064        NaN  211.096358         8.106          0   
1   204.8776  17605.3282        NaN  211.242170         8.106          1   
2   311.2118  14431.2547        NaN  211.289143         8.106          0   
3   235.1537   2538.1895        NaN  211.319643         8.106          0   
4   214.4539  14482.4849        NaN  211.350143         8.106          0   

   Week_Number  Day  Month  Year  
0            5    5      2  2010  
1            6   12      2  2010  
2            7   19      2  2010  
3            8   26      2  2010  
4            9    5      3  2010

In [172]:
# Model for MarkDown 5

x = df_markdown_notnull.drop(['MarkDown5'], axis = 1)
y = df_markdown_notnull['MarkDown5']

markdown_model_5 = RandomForestRegressor().fit(x, y)
y_pred = markdown_model_5.predict(x)
print(mean_absolute_error(y, y_pred))

# applying the model for null dataframe

x_new = df_markdown_null.drop(['MarkDown5'], axis = 1)
predicted_markdown_5 = markdown_model_5.predict(x_new)

# Inserting the predicted markdown1 values into the null dataframe

df_markdown_null['MarkDown5'] = predicted_markdown_5
df_markdown_null.head()

764.1001347407407


Store  Type    Size  Temperature  Fuel_Price   MarkDown1   MarkDown2  \
0      1     1  151315        42.31       2.572  20522.5677   3916.1645   
1      1     1  151315        38.51       2.548  24408.0508   5594.7194   
2      1     1  151315        39.93       2.514  17676.8263  10742.3213   
3      1     1  151315        46.63       2.561  11852.7496   9454.8240   
4      1     1  151315        46.50       2.625  17209.1016   3637.3314   

   MarkDown3   MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
0   216.3458  19570.7064  8460.3097  211.096358         8.106          0   
1   204.8776  17605.3282  5964.9716  211.242170         8.106          1   
2   311.2118  14431.2547  5905.7269  211.289143         8.106          0   
3   235.1537   2538.1895  6454.7869  211.319643         8.106          0   
4   214.4539  14482.4849  8334.6426  211.350143         8.106          0   

   Week_Number  Day  Month  Year  
0            5    5      2  2010  
1            6   12      2  2010  
2            7   19      2  2010  
3            8   26      2  2010  
4            9    5      3  2010

In [173]:
df_feature_notnull = pd.concat([df_markdown_null, df_markdown_notnull], axis = 0, ignore_index = True)
df_feature_notnull

Store  Type    Size  Temperature  Fuel_Price   MarkDown1   MarkDown2  \
0         1     1  151315        42.31       2.572  20522.5677   3916.1645   
1         1     1  151315        38.51       2.548  24408.0508   5594.7194   
2         1     1  151315        39.93       2.514  17676.8263  10742.3213   
3         1     1  151315        46.63       2.561  11852.7496   9454.8240   
4         1     1  151315        46.50       2.625  17209.1016   3637.3314   
...     ...   ...     ...          ...         ...         ...         ...   
8185     45     2  118221        76.05       3.639   4842.2900    975.0300   
8186     45     2  118221        77.50       3.614   9090.4800   2268.5800   
8187     45     2  118221        79.37       3.614   3789.9400   1827.3100   
8188     45     2  118221        82.84       3.737   2961.4900   1047.0700   
8189     45     2  118221        76.06       3.804    212.0200    851.7300   

      MarkDown3   MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
0      216.3458  19570.7064  8460.3097  211.096358      8.106000          0   
1      204.8776  17605.3282  5964.9716  211.242170      8.106000          1   
2      311.2118  14431.2547  5905.7269  211.289143      8.106000          0   
3      235.1537   2538.1895  6454.7869  211.319643      8.106000          0   
4      214.4539  14482.4849  8334.6426  211.350143      8.106000          0   
...         ...         ...        ...         ...           ...        ...   
8185     3.0000   2449.9700  3169.6900  192.825518      8.308551          0   
8186   582.7400   5797.4700  1514.9300  192.615082      8.249614          0   
8187    85.7200    744.8400  2150.3600  192.803314      8.287728          0   
8188   204.1900    363.0000  1059.4600  192.748473      8.581907          0   
8189     2.0600     10.8800  1864.5700  193.491386      8.590008          0   

      Week_Number  Day  Month  Year  
0               5    5      2  2010  
1               6   12      2  2010  
2               7   19      2  2010  
3               8   26      2  2010  
4               9    5      3  2010  
...           ...  ...    ...   ...  
8185           26   28      6  2013  
8186           27    5      7  2013  
8187           28   12      7  2013  
8188           29   19      7  2013  
8189           30   26      7  2013  

[8190 rows x 17 columns]

In [174]:
df_feature_notnull.isna().sum()

Store           0
Type            0
Size            0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
IsHoliday       0
Week_Number     0
Day             0
Month           0
Year            0
dtype: int64

### Sales Dataframe

In [177]:
df_sales.head()

Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  05/02/2010      24924.50      False
1      1     1  12/02/2010      46039.49       True
2      1     1  19/02/2010      41595.55      False
3      1     1  26/02/2010      19403.54      False
4      1     1  05/03/2010      21827.90      False

In [179]:
df_sales['Date'] =pd.to_datetime(df_sales['Date'], format = '%d/%m/%Y')
df_sales.head()

Store  Dept       Date  Weekly_Sales  IsHoliday
0      1     1 2010-02-05      24924.50      False
1      1     1 2010-02-12      46039.49       True
2      1     1 2010-02-19      41595.55      False
3      1     1 2010-02-26      19403.54      False
4      1     1 2010-03-05      21827.90      False

In [180]:
df_sales_2.head()

Store  Dept        Date  IsHoliday
0      1     1  2012-11-02      False
1      1     1  2012-11-09      False
2      1     1  2012-11-16      False
3      1     1  2012-11-23       True
4      1     1  2012-11-30      False

In [185]:
df_sales_2['Date'] = pd.to_datetime(df_sales_2['Date'], format= '%Y-%m-%d')
df_sales_2.head()

Store  Dept       Date  IsHoliday
0      1     1 2012-11-02      False
1      1     1 2012-11-09      False
2      1     1 2012-11-16      False
3      1     1 2012-11-23       True
4      1     1 2012-11-30      False

In [186]:
# Merging both sales dataframe

sales = pd.concat([df_sales, df_sales_2], ignore_index = True)
sales

Store  Dept       Date  Weekly_Sales  IsHoliday
0           1     1 2010-02-05      24924.50      False
1           1     1 2010-02-12      46039.49       True
2           1     1 2010-02-19      41595.55      False
3           1     1 2010-02-26      19403.54      False
4           1     1 2010-03-05      21827.90      False
...       ...   ...        ...           ...        ...
536629     45    98 2013-06-28           NaN      False
536630     45    98 2013-07-05           NaN      False
536631     45    98 2013-07-12           NaN      False
536632     45    98 2013-07-19           NaN      False
536633     45    98 2013-07-26           NaN      False

[536634 rows x 5 columns]

In [187]:
# checking the null values of weekly sales column

sales.Weekly_Sales.isna().value_counts()

Weekly_Sales
False    421570
True     115064
Name: count, dtype: int64

In [184]:
df_feature_notnull_copy = df_feature_notnull.copy()

# adding the date column to merge the sales dataframe

df_feature_notnull_copy['Date'] = pd.to_datetime(df_feature_notnull_copy[['Year', 'Month', 'Day']])
df_feature_notnull_copy

Store  Type    Size  Temperature  Fuel_Price   MarkDown1   MarkDown2  \
0         1     1  151315        42.31       2.572  20522.5677   3916.1645   
1         1     1  151315        38.51       2.548  24408.0508   5594.7194   
2         1     1  151315        39.93       2.514  17676.8263  10742.3213   
3         1     1  151315        46.63       2.561  11852.7496   9454.8240   
4         1     1  151315        46.50       2.625  17209.1016   3637.3314   
...     ...   ...     ...          ...         ...         ...         ...   
8185     45     2  118221        76.05       3.639   4842.2900    975.0300   
8186     45     2  118221        77.50       3.614   9090.4800   2268.5800   
8187     45     2  118221        79.37       3.614   3789.9400   1827.3100   
8188     45     2  118221        82.84       3.737   2961.4900   1047.0700   
8189     45     2  118221        76.06       3.804    212.0200    851.7300   

      MarkDown3   MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
0      216.3458  19570.7064  8460.3097  211.096358      8.106000          0   
1      204.8776  17605.3282  5964.9716  211.242170      8.106000          1   
2      311.2118  14431.2547  5905.7269  211.289143      8.106000          0   
3      235.1537   2538.1895  6454.7869  211.319643      8.106000          0   
4      214.4539  14482.4849  8334.6426  211.350143      8.106000          0   
...         ...         ...        ...         ...           ...        ...   
8185     3.0000   2449.9700  3169.6900  192.825518      8.308551          0   
8186   582.7400   5797.4700  1514.9300  192.615082      8.249614          0   
8187    85.7200    744.8400  2150.3600  192.803314      8.287728          0   
8188   204.1900    363.0000  1059.4600  192.748473      8.581907          0   
8189     2.0600     10.8800  1864.5700  193.491386      8.590008          0   

      Week_Number  Day  Month  Year       Date  
0               5    5      2  2010 2010-02-05  
1               6   12      2  2010 2010-02-12  
2               7   19      2  2010 2010-02-19  
3               8   26      2  2010 2010-02-26  
4               9    5      3  2010 2010-03-05  
...           ...  ...    ...   ...        ...  
8185           26   28      6  2013 2013-06-28  
8186           27    5      7  2013 2013-07-05  
8187           28   12      7  2013 2013-07-12  
8188           29   19      7  2013 2013-07-19  
8189           30   26      7  2013 2013-07-26  

[8190 rows x 18 columns]

In [188]:
df = df_feature_notnull_copy.merge(sales, on = ['Store', 'Date'], how = 'inner')
df

Store  Type    Size  Temperature  Fuel_Price   MarkDown1  MarkDown2  \
0           1     1  151315        42.31       2.572  20522.5677  3916.1645   
1           1     1  151315        42.31       2.572  20522.5677  3916.1645   
2           1     1  151315        42.31       2.572  20522.5677  3916.1645   
3           1     1  151315        42.31       2.572  20522.5677  3916.1645   
4           1     1  151315        42.31       2.572  20522.5677  3916.1645   
...       ...   ...     ...          ...         ...         ...        ...   
536629     45     2  118221        76.06       3.804    212.0200   851.7300   
536630     45     2  118221        76.06       3.804    212.0200   851.7300   
536631     45     2  118221        76.06       3.804    212.0200   851.7300   
536632     45     2  118221        76.06       3.804    212.0200   851.7300   
536633     45     2  118221        76.06       3.804    212.0200   851.7300   

        MarkDown3   MarkDown4  MarkDown5  ...  Unemployment  IsHoliday_x  \
0        216.3458  19570.7064  8460.3097  ...      8.106000            0   
1        216.3458  19570.7064  8460.3097  ...      8.106000            0   
2        216.3458  19570.7064  8460.3097  ...      8.106000            0   
3        216.3458  19570.7064  8460.3097  ...      8.106000            0   
4        216.3458  19570.7064  8460.3097  ...      8.106000            0   
...           ...         ...        ...  ...           ...          ...   
536629     2.0600     10.8800  1864.5700  ...      8.590008            0   
536630     2.0600     10.8800  1864.5700  ...      8.590008            0   
536631     2.0600     10.8800  1864.5700  ...      8.590008            0   
536632     2.0600     10.8800  1864.5700  ...      8.590008            0   
536633     2.0600     10.8800  1864.5700  ...      8.590008            0   

        Week_Number  Day  Month  Year       Date Dept  Weekly_Sales  \
0                 5    5      2  2010 2010-02-05    1      24924.50   
1                 5    5      2  2010 2010-02-05    2      50605.27   
2                 5    5      2  2010 2010-02-05    3      13740.12   
3                 5    5      2  2010 2010-02-05    4      39954.04   
4                 5    5      2  2010 2010-02-05    5      32229.38   
...             ...  ...    ...   ...        ...  ...           ...   
536629           30   26      7  2013 2013-07-26   93           NaN   
536630           30   26      7  2013 2013-07-26   94           NaN   
536631           30   26      7  2013 2013-07-26   95           NaN   
536632           30   26      7  2013 2013-07-26   97           NaN   
536633           30   26      7  2013 2013-07-26   98           NaN   

        IsHoliday_y  
0             False  
1             False  
2             False  
3             False  
4             False  
...             ...  
536629        False  
536630        False  
536631        False  
536632        False  
536633        False  

[536634 rows x 21 columns]

In [189]:
# removing the unwanted holiday column and rename the other

df.rename(columns = {'IsHoliday_x' : 'IsHoliday'}, inplace = True)
df.drop(columns = ['IsHoliday_y', 'Date'], axis = 1, inplace = True)
df.head()

Store  Type    Size  Temperature  Fuel_Price   MarkDown1  MarkDown2  \
0      1     1  151315        42.31       2.572  20522.5677  3916.1645   
1      1     1  151315        42.31       2.572  20522.5677  3916.1645   
2      1     1  151315        42.31       2.572  20522.5677  3916.1645   
3      1     1  151315        42.31       2.572  20522.5677  3916.1645   
4      1     1  151315        42.31       2.572  20522.5677  3916.1645   

   MarkDown3   MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
0   216.3458  19570.7064  8460.3097  211.096358         8.106          0   
1   216.3458  19570.7064  8460.3097  211.096358         8.106          0   
2   216.3458  19570.7064  8460.3097  211.096358         8.106          0   
3   216.3458  19570.7064  8460.3097  211.096358         8.106          0   
4   216.3458  19570.7064  8460.3097  211.096358         8.106          0   

   Week_Number  Day  Month  Year  Dept  Weekly_Sales  
0            5    5      2  2010     1      24924.50  
1            5    5      2  2010     2      50605.27  
2            5    5      2  2010     3      13740.12  
3            5    5      2  2010     4      39954.04  
4            5    5      2  2010     5      32229.38

In [190]:
df.shape

(536634, 19)

In [191]:
# Adding a column Markup for the negative markdown values, which menas a price increase

df[(df.MarkDown1 < 0) | (df.MarkDown2 < 0) | (df.MarkDown3 < 0) | (df.MarkDown4 < 0) | (df.MarkDown5 < 0)]

Store  Type   Size  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
221904     36     1  39910        77.94       3.499   238.8338    -0.2994   
221905     36     1  39910        77.94       3.499   238.8338    -0.2994   
221906     36     1  39910        77.94       3.499   238.8338    -0.2994   
221907     36     1  39910        77.94       3.499   238.8338    -0.2994   
221908     36     1  39910        77.94       3.499   238.8338    -0.2994   
...       ...   ...    ...          ...         ...        ...        ...   
504121      7     2  70713        50.70       3.870  2350.7800    -7.7600   
504122      7     2  70713        50.70       3.870  2350.7800    -7.7600   
504123      7     2  70713        50.70       3.870  2350.7800    -7.7600   
504124      7     2  70713        50.70       3.870  2350.7800    -7.7600   
504125      7     2  70713        50.70       3.870  2350.7800    -7.7600   

        MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
221904    55.7066    19.9225  1503.3537  214.615538      8.177000          2   
221905    55.7066    19.9225  1503.3537  214.615538      8.177000          2   
221906    55.7066    19.9225  1503.3537  214.615538      8.177000          2   
221907    55.7066    19.9225  1503.3537  214.615538      8.177000          2   
221908    55.7066    19.9225  1503.3537  214.615538      8.177000          2   
...           ...        ...        ...         ...           ...        ...   
504121    91.5900   166.8600   540.8900  203.766543      7.140499          0   
504122    91.5900   166.8600   540.8900  203.766543      7.140499          0   
504123    91.5900   166.8600   540.8900  203.766543      7.140499          0   
504124    91.5900   166.8600   540.8900  203.766543      7.140499          0   
504125    91.5900   166.8600   540.8900  203.766543      7.140499          0   

        Week_Number  Day  Month  Year  Dept  Weekly_Sales  
221904           36    9      9  2011     1       2029.74  
221905           36    9      9  2011     2      12030.24  
221906           36    9      9  2011     3        378.49  
221907           36    9      9  2011     4       8326.60  
221908           36    9      9  2011     5        177.50  
...             ...  ...    ...   ...   ...           ...  
504121           22   31      5  2013    94           NaN  
504122           22   31      5  2013    95           NaN  
504123           22   31      5  2013    96           NaN  
504124           22   31      5  2013    97           NaN  
504125           22   31      5  2013    98           NaN  

[3003 rows x 19 columns]

In [192]:
df['IsMarkup'] = np.where((df.MarkDown1 < 0) | (df.MarkDown2 < 0) |(df.MarkDown3 < 0) | (df.MarkDown4 < 0) | (df.MarkDown5 < 0), 1, 0)

df[(df.MarkDown1 < 0) | (df.MarkDown2 < 0) | (df.MarkDown3 < 0) | (df.MarkDown4 < 0) | (df.MarkDown5 < 0)]

Store  Type   Size  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
221904     36     1  39910        77.94       3.499   238.8338    -0.2994   
221905     36     1  39910        77.94       3.499   238.8338    -0.2994   
221906     36     1  39910        77.94       3.499   238.8338    -0.2994   
221907     36     1  39910        77.94       3.499   238.8338    -0.2994   
221908     36     1  39910        77.94       3.499   238.8338    -0.2994   
...       ...   ...    ...          ...         ...        ...        ...   
504121      7     2  70713        50.70       3.870  2350.7800    -7.7600   
504122      7     2  70713        50.70       3.870  2350.7800    -7.7600   
504123      7     2  70713        50.70       3.870  2350.7800    -7.7600   
504124      7     2  70713        50.70       3.870  2350.7800    -7.7600   
504125      7     2  70713        50.70       3.870  2350.7800    -7.7600   

        MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
221904    55.7066    19.9225  1503.3537  214.615538      8.177000          2   
221905    55.7066    19.9225  1503.3537  214.615538      8.177000          2   
221906    55.7066    19.9225  1503.3537  214.615538      8.177000          2   
221907    55.7066    19.9225  1503.3537  214.615538      8.177000          2   
221908    55.7066    19.9225  1503.3537  214.615538      8.177000          2   
...           ...        ...        ...         ...           ...        ...   
504121    91.5900   166.8600   540.8900  203.766543      7.140499          0   
504122    91.5900   166.8600   540.8900  203.766543      7.140499          0   
504123    91.5900   166.8600   540.8900  203.766543      7.140499          0   
504124    91.5900   166.8600   540.8900  203.766543      7.140499          0   
504125    91.5900   166.8600   540.8900  203.766543      7.140499          0   

        Week_Number  Day  Month  Year  Dept  Weekly_Sales  IsMarkup  
221904           36    9      9  2011     1       2029.74         1  
221905           36    9      9  2011     2      12030.24         1  
221906           36    9      9  2011     3        378.49         1  
221907           36    9      9  2011     4       8326.60         1  
221908           36    9      9  2011     5        177.50         1  
...             ...  ...    ...   ...   ...           ...       ...  
504121           22   31      5  2013    94           NaN         1  
504122           22   31      5  2013    95           NaN         1  
504123           22   31      5  2013    96           NaN         1  
504124           22   31      5  2013    97           NaN         1  
504125           22   31      5  2013    98           NaN         1  

[3003 rows x 20 columns]

In [194]:
df.head()

Store  Type    Size  Temperature  Fuel_Price   MarkDown1  MarkDown2  \
0      1     1  151315        42.31       2.572  20522.5677  3916.1645   
1      1     1  151315        42.31       2.572  20522.5677  3916.1645   
2      1     1  151315        42.31       2.572  20522.5677  3916.1645   
3      1     1  151315        42.31       2.572  20522.5677  3916.1645   
4      1     1  151315        42.31       2.572  20522.5677  3916.1645   

   MarkDown3   MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
0   216.3458  19570.7064  8460.3097  211.096358         8.106          0   
1   216.3458  19570.7064  8460.3097  211.096358         8.106          0   
2   216.3458  19570.7064  8460.3097  211.096358         8.106          0   
3   216.3458  19570.7064  8460.3097  211.096358         8.106          0   
4   216.3458  19570.7064  8460.3097  211.096358         8.106          0   

   Week_Number  Day  Month  Year  Dept  Weekly_Sales  IsMarkup  
0            5    5      2  2010     1      24924.50         0  
1            5    5      2  2010     2      50605.27         0  
2            5    5      2  2010     3      13740.12         0  
3            5    5      2  2010     4      39954.04         0  
4            5    5      2  2010     5      32229.38         0

Training the model to predict the missing weekly sales value

In [195]:
#splititng into two dataframes with null and not null

df_train = df[df.Weekly_Sales.isna() == False]
df_test = df[df.Weekly_Sales.isna() == True]

print(df_train.Weekly_Sales.isna().sum())
df_test.Weekly_Sales.isna().sum()

0


115064

In [196]:
x = df_train.drop('Weekly_Sales', axis = 1)
y = df_train['Weekly_Sales']

x_train,x_test, y_train,y_test = train_test_split(x,y, test_size  = 0.2, random_state = 42)
model = RandomForestRegressor().fit(x_train, y_train)

y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

print("Train MAE: ", mean_absolute_error(y_train, y_train_pred))
print("Test MAE: ", mean_absolute_error(y_test, y_test_pred))

Train MAE:  510.0219221039804
Test MAE:  1382.4245663472261


In [197]:
x_new = df_test.drop('Weekly_Sales', axis = 1)

predicted_weekly_sales = model.predict(x_new)

In [198]:
df_test_1 = df_test.copy()

df_test_1['Weekly_Sales'] = predicted_weekly_sales

df_test_1.head()

Store  Type    Size  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
273795      1     1  151315        55.32       3.386    6766.44     5147.7   
273796      1     1  151315        55.32       3.386    6766.44     5147.7   
273797      1     1  151315        55.32       3.386    6766.44     5147.7   
273798      1     1  151315        55.32       3.386    6766.44     5147.7   
273799      1     1  151315        55.32       3.386    6766.44     5147.7   

        MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
273795      50.82     3639.9    2737.42  223.462779         6.573          0   
273796      50.82     3639.9    2737.42  223.462779         6.573          0   
273797      50.82     3639.9    2737.42  223.462779         6.573          0   
273798      50.82     3639.9    2737.42  223.462779         6.573          0   
273799      50.82     3639.9    2737.42  223.462779         6.573          0   

        Week_Number  Day  Month  Year  Dept  Weekly_Sales  IsMarkup  
273795           44    2     11  2012     1    33805.8050         0  
273796           44    2     11  2012     2    45978.2110         0  
273797           44    2     11  2012     3    10811.0567         0  
273798           44    2     11  2012     4    39188.3594         0  
273799           44    2     11  2012     5    27069.2105         0

In [199]:
df_test_1.shape

(115064, 20)

In [202]:
df_fin = pd.concat([df_train, df_test_1], axis = 0, ignore_index = True)

df_fin

Store  Type    Size  Temperature  Fuel_Price   MarkDown1  MarkDown2  \
0           1     1  151315        42.31       2.572  20522.5677  3916.1645   
1           1     1  151315        42.31       2.572  20522.5677  3916.1645   
2           1     1  151315        42.31       2.572  20522.5677  3916.1645   
3           1     1  151315        42.31       2.572  20522.5677  3916.1645   
4           1     1  151315        42.31       2.572  20522.5677  3916.1645   
...       ...   ...     ...          ...         ...         ...        ...   
536629     45     2  118221        76.06       3.804    212.0200   851.7300   
536630     45     2  118221        76.06       3.804    212.0200   851.7300   
536631     45     2  118221        76.06       3.804    212.0200   851.7300   
536632     45     2  118221        76.06       3.804    212.0200   851.7300   
536633     45     2  118221        76.06       3.804    212.0200   851.7300   

        MarkDown3   MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday  \
0        216.3458  19570.7064  8460.3097  211.096358      8.106000          0   
1        216.3458  19570.7064  8460.3097  211.096358      8.106000          0   
2        216.3458  19570.7064  8460.3097  211.096358      8.106000          0   
3        216.3458  19570.7064  8460.3097  211.096358      8.106000          0   
4        216.3458  19570.7064  8460.3097  211.096358      8.106000          0   
...           ...         ...        ...         ...           ...        ...   
536629     2.0600     10.8800  1864.5700  193.491386      8.590008          0   
536630     2.0600     10.8800  1864.5700  193.491386      8.590008          0   
536631     2.0600     10.8800  1864.5700  193.491386      8.590008          0   
536632     2.0600     10.8800  1864.5700  193.491386      8.590008          0   
536633     2.0600     10.8800  1864.5700  193.491386      8.590008          0   

        Week_Number  Day  Month  Year  Dept  Weekly_Sales  IsMarkup  
0                 5    5      2  2010     1    24924.5000         0  
1                 5    5      2  2010     2    50605.2700         0  
2                 5    5      2  2010     3    13740.1200         0  
3                 5    5      2  2010     4    39954.0400         0  
4                 5    5      2  2010     5    32229.3800         0  
...             ...  ...    ...   ...   ...           ...       ...  
536629           30   26      7  2013    93     3391.6125         0  
536630           30   26      7  2013    94     4029.5197         0  
536631           30   26      7  2013    95    57285.5943         0  
536632           30   26      7  2013    97     5697.8791         0  
536633           30   26      7  2013    98      853.3786         0  

[536634 rows x 20 columns]

In [213]:
df_fin.isna().sum()

Store           0
Type            0
Size            0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
IsHoliday       0
Week_Number     0
Day             0
Month           0
Year            0
Dept            0
Weekly_Sales    0
IsMarkup        0
dtype: int64

In [207]:
# Arranging the columns in certain order to understand

df_final = df_fin[['Store', 'Type', 'Dept', 'Size', 'Temperature', 'Fuel_Price', 'MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5',
                   'IsMarkup', 'Week_Number',  'IsHoliday', 'CPI', 'Unemployment', 'Day', 'Month', 'Year', 'Weekly_Sales']]
df_final

Store  Type  Dept    Size  Temperature  Fuel_Price   MarkDown1  \
0           1     1     1  151315        42.31       2.572  20522.5677   
1           1     1     2  151315        42.31       2.572  20522.5677   
2           1     1     3  151315        42.31       2.572  20522.5677   
3           1     1     4  151315        42.31       2.572  20522.5677   
4           1     1     5  151315        42.31       2.572  20522.5677   
...       ...   ...   ...     ...          ...         ...         ...   
536629     45     2    93  118221        76.06       3.804    212.0200   
536630     45     2    94  118221        76.06       3.804    212.0200   
536631     45     2    95  118221        76.06       3.804    212.0200   
536632     45     2    97  118221        76.06       3.804    212.0200   
536633     45     2    98  118221        76.06       3.804    212.0200   

        MarkDown2  MarkDown3   MarkDown4  MarkDown5  IsMarkup  Week_Number  \
0       3916.1645   216.3458  19570.7064  8460.3097         0            5   
1       3916.1645   216.3458  19570.7064  8460.3097         0            5   
2       3916.1645   216.3458  19570.7064  8460.3097         0            5   
3       3916.1645   216.3458  19570.7064  8460.3097         0            5   
4       3916.1645   216.3458  19570.7064  8460.3097         0            5   
...           ...        ...         ...        ...       ...          ...   
536629   851.7300     2.0600     10.8800  1864.5700         0           30   
536630   851.7300     2.0600     10.8800  1864.5700         0           30   
536631   851.7300     2.0600     10.8800  1864.5700         0           30   
536632   851.7300     2.0600     10.8800  1864.5700         0           30   
536633   851.7300     2.0600     10.8800  1864.5700         0           30   

        IsHoliday         CPI  Unemployment  Day  Month  Year  Weekly_Sales  
0               0  211.096358      8.106000    5      2  2010    24924.5000  
1               0  211.096358      8.106000    5      2  2010    50605.2700  
2               0  211.096358      8.106000    5      2  2010    13740.1200  
3               0  211.096358      8.106000    5      2  2010    39954.0400  
4               0  211.096358      8.106000    5      2  2010    32229.3800  
...           ...         ...           ...  ...    ...   ...           ...  
536629          0  193.491386      8.590008   26      7  2013     3391.6125  
536630          0  193.491386      8.590008   26      7  2013     4029.5197  
536631          0  193.491386      8.590008   26      7  2013    57285.5943  
536632          0  193.491386      8.590008   26      7  2013     5697.8791  
536633          0  193.491386      8.590008   26      7  2013      853.3786  

[536634 rows x 20 columns]

In [ ]:
final_dataset = df_final.copy

In [214]:
# Replacing the some numerical values to export as a clean dataset for future reference

holiday = {0: 'No Holiday', 
           1: 'Super Bowl',
           2: 'Labor Day',
           3: 'Thanksgiving',
           4: 'Christmas'}

for_type = {1: "A",
            2: "B",
            3: "C"}

final_dataset = df_final.copy()

final_dataset['IsHoliday'] = final_dataset['IsHoliday'].map(holiday)
final_dataset['Type'] = final_dataset['Type'].map(for_type)
final_dataset

Store Type  Dept    Size  Temperature  Fuel_Price   MarkDown1  \
0           1    A     1  151315        42.31       2.572  20522.5677   
1           1    A     2  151315        42.31       2.572  20522.5677   
2           1    A     3  151315        42.31       2.572  20522.5677   
3           1    A     4  151315        42.31       2.572  20522.5677   
4           1    A     5  151315        42.31       2.572  20522.5677   
...       ...  ...   ...     ...          ...         ...         ...   
536629     45    B    93  118221        76.06       3.804    212.0200   
536630     45    B    94  118221        76.06       3.804    212.0200   
536631     45    B    95  118221        76.06       3.804    212.0200   
536632     45    B    97  118221        76.06       3.804    212.0200   
536633     45    B    98  118221        76.06       3.804    212.0200   

        MarkDown2  MarkDown3   MarkDown4  MarkDown5  IsMarkup  Week_Number  \
0       3916.1645   216.3458  19570.7064  8460.3097         0            5   
1       3916.1645   216.3458  19570.7064  8460.3097         0            5   
2       3916.1645   216.3458  19570.7064  8460.3097         0            5   
3       3916.1645   216.3458  19570.7064  8460.3097         0            5   
4       3916.1645   216.3458  19570.7064  8460.3097         0            5   
...           ...        ...         ...        ...       ...          ...   
536629   851.7300     2.0600     10.8800  1864.5700         0           30   
536630   851.7300     2.0600     10.8800  1864.5700         0           30   
536631   851.7300     2.0600     10.8800  1864.5700         0           30   
536632   851.7300     2.0600     10.8800  1864.5700         0           30   
536633   851.7300     2.0600     10.8800  1864.5700         0           30   

         IsHoliday         CPI  Unemployment  Day  Month  Year  Weekly_Sales  
0       No Holiday  211.096358      8.106000    5      2  2010    24924.5000  
1       No Holiday  211.096358      8.106000    5      2  2010    50605.2700  
2       No Holiday  211.096358      8.106000    5      2  2010    13740.1200  
3       No Holiday  211.096358      8.106000    5      2  2010    39954.0400  
4       No Holiday  211.096358      8.106000    5      2  2010    32229.3800  
...            ...         ...           ...  ...    ...   ...           ...  
536629  No Holiday  193.491386      8.590008   26      7  2013     3391.6125  
536630  No Holiday  193.491386      8.590008   26      7  2013     4029.5197  
536631  No Holiday  193.491386      8.590008   26      7  2013    57285.5943  
536632  No Holiday  193.491386      8.590008   26      7  2013     5697.8791  
536633  No Holiday  193.491386      8.590008   26      7  2013      853.3786  

[536634 rows x 20 columns]

In [216]:
# Exporting to a csv file for further usage

final_dataset.to_csv('combined_clean_dataset.csv', index = False)

df_final.to_csv('combined_ml_dataset.csv', index = False)

In [217]:
df_combined = pd.read_csv(r'/Users/gokul/My Apple/vs_code_practice/retail_sales_forecast/combined_clean_dataset.csv')

df_combined.head()

Store Type  Dept    Size  Temperature  Fuel_Price   MarkDown1  MarkDown2  \
0      1    A     1  151315        42.31       2.572  20522.5677  3916.1645   
1      1    A     2  151315        42.31       2.572  20522.5677  3916.1645   
2      1    A     3  151315        42.31       2.572  20522.5677  3916.1645   
3      1    A     4  151315        42.31       2.572  20522.5677  3916.1645   
4      1    A     5  151315        42.31       2.572  20522.5677  3916.1645   

   MarkDown3   MarkDown4  MarkDown5  IsMarkup  Week_Number   IsHoliday  \
0   216.3458  19570.7064  8460.3097         0            5  No Holiday   
1   216.3458  19570.7064  8460.3097         0            5  No Holiday   
2   216.3458  19570.7064  8460.3097         0            5  No Holiday   
3   216.3458  19570.7064  8460.3097         0            5  No Holiday   
4   216.3458  19570.7064  8460.3097         0            5  No Holiday   

          CPI  Unemployment  Day  Month  Year  Weekly_Sales  
0  211.096358         8.106    5      2  2010      24924.50  
1  211.096358         8.106    5      2  2010      50605.27  
2  211.096358         8.106    5      2  2010      13740.12  
3  211.096358         8.106    5      2  2010      39954.04  
4  211.096358         8.106    5      2  2010      32229.38